(()=>{
const $=id=>document.getElementById(id);
const TF={
 '1m':{sec:60,src:'1m'},'2m':{sec:120,src:'1m'},'3m':{sec:180,src:'1m'},
 '5m':{sec:300,src:'5m'},'10m':{sec:600,src:'5m'},'15m':{sec:900,src:'15m'},
 '30m':{sec:1800,src:'30m'},'45m':{sec:2700,src:'15m'},'1h':{sec:3600,src:'1h'},
 '2h':{sec:7200,src:'1h'},'3h':{sec:10800,src:'1h'},'4h':{sec:14400,src:'1h'},
 '6h':{sec:21600,src:'1h'},'8h':{sec:28800,src:'1h'},'12h':{sec:43200,src:'1h'},
 '1d':{sec:86400,src:'1h'},'3d':{sec:259200,src:'1h'},'1w':{sec:604800,src:'1h'}
};
let active='15m',chartSource='';
function valid(v){return TF[v]?v:null}
function sync(v){v=valid(v)||active;active=v;for(const id of ['tf','qtf']){const e=$(id);if(e&&[...e.options].some(o=>o.value===v)&&e.value!==v)e.value=v}document.querySelectorAll('#quickTf [data-tf]').forEach(b=>b.classList.toggle('active',b.dataset.tf===v));const w=$('waterTf');if(w)w.textContent=v.toUpperCase();paintSource();updateCountdown();window.dispatchEvent(new CustomEvent('qubic:timeframe',{detail:{timeframe:v}}))}
function paintSource(){const t=$('chartToast');if(t){t.textContent=chartSource?`${active.toUpperCase()} · ${chartSource} OHLC · LOCAL TIME`:'';t.style.display=chartSource?'block':'none'}const r=$('refSources');if(r&&chartSource)r.textContent=`Chart source · ${chartSource} · local candle boundaries`}
function londonOffsetSec(ts){const d=new Date(+ts*1000);const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(d).reduce((o,p)=>(o[p.type]=p.value,o),{});const asUTC=Date.UTC(+parts.year,+parts.month-1,+parts.day,+parts.hour,+parts.minute,+parts.second)/1000;return asUTC-(+ts)}
function ukBucket(t,sec,tf){t=+t;const off=londonOffsetSec(t),local=t+off;if(tf==='1w'){const d=new Date(local*1000),dow=(d.getUTCDay()+6)%7;const localMid=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())/1000;const localStart=localMid-dow*86400;let guess=localStart-off;for(let i=0;i<2;i++)guess=localStart-londonOffsetSec(guess);return guess}const localBucket=Math.floor(local/sec)*sec;let guess=localBucket-off;for(let i=0;i<2;i++)guess=localBucket-londonOffsetSec(guess);return guess}
function nextBoundary(nowSec,tf){const cfg=TF[tf]||TF['15m'];let start=ukBucket(nowSec,cfg.sec,tf);let next=start+cfg.sec;while(next<=nowSec){start=next;next=start+cfg.sec}return next}
function formatRemaining(s){s=Math.max(0,Math.ceil(s));const d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60),sec=s%60;if(d)return `${d}d ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;if(h)return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
function localClock(){return new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())}
function updateCountdown(){const el=$('candleCountdown');if(!el)return;const now=Date.now()/1000,rem=nextBoundary(now,active)-now;el.textContent=`${formatRemaining(rem)} · ${localClock()}`;el.setAttribute('aria-label',`Candle closes in ${formatRemaining(rem)}. Local time ${localClock()}`)}
function clean(rows){const m=new Map();for(const x of rows||[]){const time=+x.time,o=+x.open,h=+x.high,l=+x.low,c=+x.close,v=+x.volume||0;if(!Number.isFinite(time)||o<=0||h<=0||l<=0||c<=0||h<Math.max(o,c)||l>Math.min(o,c))continue;m.set(time,{time,open:o,high:h,low:l,close:c,volume:v})}return [...m.values()].sort((a,b)=>a.time-b.time)}
function aggregate(rows,tf){const cfg=TF[tf];if(!cfg)return clean(rows);const src=clean(rows);const needsUK=cfg.src!==tf||['4h','1d','3d','1w'].includes(tf);if(!needsUK)return src;const out=[];let c=null;for(const x of src){const k=ukBucket(x.time,cfg.sec,tf);if(!c||c.time!==k){if(c)out.push(c);c={time:k,open:x.open,high:x.high,low:x.low,close:x.close,volume:x.volume}}else{c.high=Math.max(c.high,x.high);c.low=Math.min(c.low,x.low);c.close=x.close;c.volume+=x.volume}}if(c)out.push(c);return clean(out)}
function chooseLimit(tf){const s=TF[tf]?.src;if(['1d','3d','1w'].includes(tf))return 1000;return s==='1m'?1000:s==='5m'?1000:s==='15m'?900:s==='30m'?700:s==='1h'?1000:700}
const nf=window.fetch.bind(window);
async function gateFallback(cfg,tf,limit,init){const u=new URL('/api/mobile-candles',location.origin);u.searchParams.set('interval',cfg.src);u.searchParams.set('limit',String(limit));u.searchParams.set('t',String(Date.now()));const r=await nf(u.pathname+u.search,init);if(!r.ok)return null;const j=await r.json();if(!j?.ok||!Array.isArray(j.candles))return null;const candles=aggregate(j.candles,tf);if(candles.length<12)return null;chartSource='GATE';paintSource();return new Response(JSON.stringify({...j,interval:tf,source:'GATE',sourceInterval:cfg.src,requestedInterval:tf,aligned:true,timeZone:'Europe/London',boundaryMode:'UK_LOCAL',candles}),{status:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}
window.fetch=async(input,init)=>{let raw=typeof input==='string'?input:(input?.url||'');if(!raw.includes('/api/mobile-candles'))return nf(input,init);const tf=active,cfg=TF[tf]||TF['15m'],limit=chooseLimit(tf);try{const u=new URL('/api/active-candles',location.origin);u.searchParams.set('interval',cfg.src);u.searchParams.set('limit',String(limit));u.searchParams.set('requested',tf);if(chartSource)u.searchParams.set('prefer',chartSource);u.searchParams.set('t',String(Date.now()));const r=await nf(u.pathname+u.search,init);if(r.ok){const j=await r.clone().json();if(j?.ok&&Array.isArray(j.candles)){const candles=aggregate(j.candles,tf);const min=tf==='1m'?40:tf==='5m'?32:tf==='15m'?28:12;if(candles.length>=min){chartSource=String(j.source||'GATE').toUpperCase();paintSource();return new Response(JSON.stringify({...j,interval:tf,sourceInterval:cfg.src,requestedInterval:tf,aligned:true,timeZone:'Europe/London',boundaryMode:'UK_LOCAL',candles}),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}}}const fb=await gateFallback(cfg,tf,limit,init);return fb||r}catch{const fb=await gateFallback(cfg,tf,limit,init);return fb||nf(input,init)}};
function localTime(ts,withDate=false){const d=new Date(+ts*1000);return new Intl.DateTimeFormat(undefined,{day:withDate?'2-digit':undefined,month:withDate?'short':undefined,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(d)}
if(window.LightweightCharts?.createChart){const cc=window.LightweightCharts.createChart.bind(window.LightweightCharts);window.LightweightCharts.createChart=(el,opt={})=>{const chart=cc(el,{...opt,localization:{...(opt.localization||{}),timeFormatter:t=>localTime(t,true)},timeScale:{...(opt.timeScale||{}),timeVisible:true,secondsVisible:false,tickMarkFormatter:t=>localTime(t,false)}});window.__QubicChart=chart;const ac=chart.addCandlestickSeries?.bind(chart),ah=chart.addHistogramSeries?.bind(chart);if(ac)chart.addCandlestickSeries=(...a)=>{const s=ac(...a);if(!window.__QubicCandleSeries)window.__QubicCandleSeries=s;return s};if(ah)chart.addHistogramSeries=(...a)=>{const s=ah(...a);if(!window.__QubicVolumeSeries)window.__QubicVolumeSeries=s;return s};return chart}}
function bind(){for(const id of ['tf','qtf']){$(id)?.addEventListener('change',e=>sync(e.target.value),true)}document.querySelectorAll('#quickTf [data-tf]').forEach(b=>b.addEventListener('click',()=>sync(b.dataset.tf),true));for(const id of ['tf','qtf']){const e=$(id);if(e)[...e.options].forEach(o=>{if(/^(10|15|30|45)s$/.test(o.value))o.remove()})}const ant=$('antStatus');if(ant&&!ant.textContent.trim())ant.style.display='none';sync(valid($('qtf')?.value)||valid($('tf')?.value)||'15m');updateCountdown();setInterval(updateCountdown,1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
window.__QubicChartCore={get timeframe(){return active},get source(){return chartSource},sync,TF,nextBoundary};
})();