(()=>{
const $=id=>document.getElementById(id);
const TF={
 '1m':{sec:60,src:'1m'},'2m':{sec:120,src:'1m'},'3m':{sec:180,src:'1m'},
 '5m':{sec:300,src:'5m'},'10m':{sec:600,src:'5m'},'15m':{sec:900,src:'15m'},
 '30m':{sec:1800,src:'30m'},'45m':{sec:2700,src:'15m'},'1h':{sec:3600,src:'1h'},
 '2h':{sec:7200,src:'1h'},'3h':{sec:10800,src:'1h'},'4h':{sec:14400,src:'1h'},
 '6h':{sec:21600,src:'1h'},'8h':{sec:28800,src:'1h'},'12h':{sec:43200,src:'1h'},
 '1d':{sec:86400,src:'1h'},'3d':{sec:259200,src:'1h'},'1w':{sec:604800,src:'1h'}
};
let active='15m',chartSource='',countdownTimer=null,lastCountdownText='',lastPrice=null,lastOpen=null;
const priceLines=[];
const localTickFmt=new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
const localDateTickFmt=new Intl.DateTimeFormat(undefined,{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
const londonPartsFmt=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});
function valid(v){return TF[v]?v:null}
function sync(v){v=valid(v)||active;if(v===active){updateCountdown();return}active=v;for(const id of ['tf','qtf']){const e=$(id);if(e&&[...e.options].some(o=>o.value===v)&&e.value!==v)e.value=v}document.querySelectorAll('#quickTf [data-tf]').forEach(b=>b.classList.toggle('active',b.dataset.tf===v));const w=$('waterTf');if(w)w.textContent=v.toUpperCase();paintSource();updateCountdown();window.dispatchEvent(new CustomEvent('qubic:timeframe',{detail:{timeframe:v}}))}
function paintSource(){const r=$('refSources');if(r&&chartSource)r.textContent=`Chart source · ${chartSource} · UK-aligned candle boundaries`}
function londonOffsetSec(ts){const d=new Date(+ts*1000);const parts=londonPartsFmt.formatToParts(d).reduce((o,p)=>(o[p.type]=p.value,o),{});const asUTC=Date.UTC(+parts.year,+parts.month-1,+parts.day,+parts.hour,+parts.minute,+parts.second)/1000;return asUTC-(+ts)}
function ukBucket(t,sec,tf){t=+t;const off=londonOffsetSec(t),local=t+off;if(tf==='1w'){const d=new Date(local*1000),dow=(d.getUTCDay()+6)%7;const localMid=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())/1000;const localStart=localMid-dow*86400;let guess=localStart-off;for(let i=0;i<2;i++)guess=localStart-londonOffsetSec(guess);return guess}const localBucket=Math.floor(local/sec)*sec;let guess=localBucket-off;for(let i=0;i<2;i++)guess=localBucket-londonOffsetSec(guess);return guess}
function nextBoundary(nowSec,tf){const cfg=TF[tf]||TF['15m'],start=ukBucket(nowSec,cfg.sec,tf);let next=ukBucket(nowSec+cfg.sec+10800,cfg.sec,tf);if(!(next>start))next=start+cfg.sec;return next}
function formatRemaining(s){s=Math.max(0,Math.ceil(s));const d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60),sec=s%60;if(d)return `${d}d ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;if(h)return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
function priceColor(){return Number.isFinite(lastOpen)&&Number.isFinite(lastPrice)&&lastPrice<lastOpen?'#f23645':'#089981'}
function refreshPriceLines(){if(!Number.isFinite(lastPrice)||!priceLines.length)return;const color=priceColor(),title=lastCountdownText||'--:--';for(const line of priceLines){try{line.applyOptions({price:lastPrice,title,color,axisLabelVisible:true,lineVisible:false,axisLabelColor:color,axisLabelTextColor:'#ffffff'})}catch{try{line.applyOptions({price:lastPrice,title,color,axisLabelVisible:true,lineVisible:false})}catch{}}}}
function updateCountdown(){if(document.hidden)return;const now=Date.now()/1000,text=formatRemaining(nextBoundary(now,active)-now);if(text!==lastCountdownText){lastCountdownText=text;refreshPriceLines()}}
function scheduleCountdown(){if(countdownTimer)clearTimeout(countdownTimer);if(document.hidden)return;updateCountdown();countdownTimer=setTimeout(scheduleCountdown,1000-(Date.now()%1000)+24)}
function trackPoint(p){if(!p)return;const price=Number.isFinite(+p.close)?+p.close:Number.isFinite(+p.value)?+p.value:null;if(Number.isFinite(price))lastPrice=price;if(Number.isFinite(+p.open))lastOpen=+p.open;refreshPriceLines()}
function attachAxisCountdown(series,type){try{series.applyOptions({lastValueVisible:false,priceLineVisible:false})}catch{}let line=null;try{line=series.createPriceLine({price:Number.isFinite(lastPrice)?lastPrice:0,title:lastCountdownText||'--:--',color:'#089981',lineVisible:false,axisLabelVisible:true,axisLabelTextColor:'#ffffff'})}catch{}if(line)priceLines.push(line);const sd=series.setData?.bind(series),up=series.update?.bind(series);if(sd)series.setData=a=>{const r=sd(a);if(Array.isArray(a)&&a.length)trackPoint(a[a.length-1]);return r};if(up)series.update=p=>{const r=up(p);trackPoint(p);return r};return series}
function clean(rows){const m=new Map();for(const x of rows||[]){const time=+x.time,o=+x.open,h=+x.high,l=+x.low,c=+x.close,v=+x.volume||0;if(!Number.isFinite(time)||o<=0||h<=0||l<=0||c<=0||h<Math.max(o,c)||l>Math.min(o,c))continue;m.set(time,{time,open:o,high:h,low:l,close:c,volume:v})}return [...m.values()].sort((a,b)=>a.time-b.time)}
function aggregate(rows,tf){const cfg=TF[tf];if(!cfg)return clean(rows);const src=clean(rows);const needsUK=cfg.src!==tf||['4h','1d','3d','1w'].includes(tf);if(!needsUK)return src;const out=[];let c=null;for(const x of src){const k=ukBucket(x.time,cfg.sec,tf);if(!c||c.time!==k){if(c)out.push(c);c={time:k,open:x.open,high:x.high,low:x.low,close:x.close,volume:x.volume}}else{c.high=Math.max(c.high,x.high);c.low=Math.min(c.low,x.low);c.close=x.close;c.volume+=x.volume}}if(c)out.push(c);return clean(out)}
function chooseLimit(tf){const s=TF[tf]?.src;if(['1d','3d','1w'].includes(tf))return 1000;return s==='1m'?1000:s==='5m'?1000:s==='15m'?900:s==='30m'?700:s==='1h'?1000:700}
const nf=window.fetch.bind(window);
async function gateFallback(cfg,tf,limit,init){const u=new URL('/api/mobile-candles',location.origin);u.searchParams.set('interval',cfg.src);u.searchParams.set('limit',String(limit));u.searchParams.set('t',String(Date.now()));const r=await nf(u.pathname+u.search,init);if(!r.ok)return null;const j=await r.json();if(!j?.ok||!Array.isArray(j.candles))return null;const candles=aggregate(j.candles,tf);if(candles.length<12)return null;chartSource='GATE';paintSource();return new Response(JSON.stringify({...j,interval:tf,source:'GATE',sourceInterval:cfg.src,requestedInterval:tf,aligned:true,timeZone:'Europe/London',boundaryMode:'UK_LOCAL',candles}),{status:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}
window.fetch=async(input,init)=>{let raw=typeof input==='string'?input:(input?.url||'');if(!raw.includes('/api/mobile-candles'))return nf(input,init);const tf=active,cfg=TF[tf]||TF['15m'],limit=chooseLimit(tf);try{const u=new URL('/api/active-candles',location.origin);u.searchParams.set('interval',cfg.src);u.searchParams.set('limit',String(limit));u.searchParams.set('requested',tf);if(chartSource)u.searchParams.set('prefer',chartSource);u.searchParams.set('t',String(Date.now()));const r=await nf(u.pathname+u.search,init);if(r.ok){const j=await r.clone().json();if(j?.ok&&Array.isArray(j.candles)){const candles=aggregate(j.candles,tf);const min=tf==='1m'?40:tf==='5m'?32:tf==='15m'?28:12;if(candles.length>=min){chartSource=String(j.source||'GATE').toUpperCase();paintSource();return new Response(JSON.stringify({...j,interval:tf,sourceInterval:cfg.src,requestedInterval:tf,aligned:true,timeZone:'Europe/London',boundaryMode:'UK_LOCAL',candles}),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}}}const fb=await gateFallback(cfg,tf,limit,init);return fb||r}catch{const fb=await gateFallback(cfg,tf,limit,init);return fb||nf(input,init)}};
function localTime(ts,withDate=false){return (withDate?localDateTickFmt:localTickFmt).format(new Date(+ts*1000))}
if(window.LightweightCharts?.createChart){const cc=window.LightweightCharts.createChart.bind(window.LightweightCharts);window.LightweightCharts.createChart=(el,opt={})=>{const chart=cc(el,{...opt,localization:{...(opt.localization||{}),timeFormatter:t=>localTime(t,true)},timeScale:{...(opt.timeScale||{}),timeVisible:true,secondsVisible:false,tickMarkFormatter:t=>localTime(t,false)}});window.__QubicChart=chart;const ac=chart.addCandlestickSeries?.bind(chart),al=chart.addLineSeries?.bind(chart),ah=chart.addHistogramSeries?.bind(chart);if(ac)chart.addCandlestickSeries=(...a)=>{const s=attachAxisCountdown(ac(...a),'candle');window.__QubicCandleSeries=s;window.__QubicChart=chart;window.dispatchEvent(new CustomEvent('qubic:chart-series',{detail:{type:'candlestick'}}));return s};if(al)chart.addLineSeries=(...a)=>attachAxisCountdown(al(...a),'line');if(ah)chart.addHistogramSeries=(...a)=>{const s=ah(...a);window.__QubicVolumeSeries=s;return s};return chart}}
function bind(){for(const id of ['tf','qtf']){$(id)?.addEventListener('change',e=>sync(e.target.value),true)}document.querySelectorAll('#quickTf [data-tf]').forEach(b=>b.addEventListener('click',()=>sync(b.dataset.tf),true));for(const id of ['tf','qtf']){const e=$(id);if(e)[...e.options].forEach(o=>{if(/^(10|15|30|45)s$/.test(o.value))o.remove()})}const ant=$('antStatus');if(ant&&!ant.textContent.trim())ant.style.display='none';const old=$('candleCountdown');if(old)old.remove();const pc=document.querySelector('.priceCountdown');if(pc)pc.style.display='block';active=valid($('qtf')?.value)||valid($('tf')?.value)||'15m';sync(active);scheduleCountdown();document.addEventListener('visibilitychange',scheduleCountdown,{passive:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
window.__QubicChartCore={get timeframe(){return active},get source(){return chartSource},get countdown(){return lastCountdownText},sync,TF,nextBoundary};
})();