(()=>{
const $=id=>document.getElementById(id);
const periods=[9,20,50,200];
const series={};
let rows=[],loading=false,chartRef=null;
function ema(data,p){if(!Array.isArray(data)||data.length<p)return[];const k=2/(p+1);let seed=data.slice(0,p).reduce((s,x)=>s+(+x.close||0),0)/p,v=seed,out=[{time:+data[p-1].time,value:seed}];for(let i=p;i<data.length;i++){v=(+data[i].close)*k+v*(1-k);out.push({time:+data[i].time,value:v})}return out}
function regression(data){if(!Array.isArray(data)||data.length<20)return{mid:[],up:[],down:[]};const n=Math.min(120,data.length),a=data.slice(-n),sx=n*(n-1)/2,sxx=(n-1)*n*(2*n-1)/6,sy=a.reduce((s,x)=>s+(+x.close||0),0),sxy=a.reduce((s,x,i)=>s+i*(+x.close||0),0),den=n*sxx-sx*sx;if(!den)return{mid:[],up:[],down:[]};const m=(n*sxy-sx*sy)/den,b=(sy-m*sx)/n,res=a.map((x,i)=>(+x.close)-(b+m*i)),sd=Math.sqrt(res.reduce((s,v)=>s+v*v,0)/Math.max(1,n-2)),mid=a.map((x,i)=>({time:+x.time,value:b+m*i}));return{mid,up:mid.map(x=>({time:x.time,value:x.value+2*sd})),down:mid.map(x=>({time:x.time,value:x.value-2*sd}))}}
function resetSeries(){for(const k of Object.keys(series))delete series[k];chartRef=null}
function ensureSeries(){const c=window.__QubicChart;if(!c||typeof c.addLineSeries!=='function')return false;if(chartRef&&chartRef!==c)resetSeries();chartRef=c;for(const p of periods){if(!series[p]){const color=document.querySelector(`.emaColor[data-ema="${p}"]`)?.value||'#ffffff';series[p]=c.addLineSeries({color,lineWidth:p===200?2:2,lastValueVisible:false,priceLineVisible:false,visible:false,priceFormat:{type:'price',precision:10,minMove:.0000000001}})}}if(!series.regMid){series.regMid=c.addLineSeries({lineWidth:2,lastValueVisible:false,priceLineVisible:false,visible:false,priceFormat:{type:'price',precision:10,minMove:.0000000001}});series.regUp=c.addLineSeries({lineWidth:1,lineStyle:2,lastValueVisible:false,priceLineVisible:false,visible:false,priceFormat:{type:'price',precision:10,minMove:.0000000001}});series.regDown=c.addLineSeries({lineWidth:1,lineStyle:2,lastValueVisible:false,priceLineVisible:false,visible:false,priceFormat:{type:'price',precision:10,minMove:.0000000001}})}return true}
function paint(){if(!rows.length||!ensureSeries())return false;for(const p of periods){const box=$(`ema${p}`),on=!!box?.checked;try{series[p].setData(ema(rows,p));series[p].applyOptions({visible:on})}catch(e){console.warn('EMA '+p,e)}}const regOn=!!$('cvdToggle')?.checked,r=regression(rows);try{series.regMid.setData(r.mid);series.regUp.setData(r.up);series.regDown.setData(r.down);[series.regMid,series.regUp,series.regDown].forEach(s=>s.applyOptions({visible:regOn}))}catch(e){console.warn('regression indicator',e)}try{window.__QubicVolumeSeries?.applyOptions({visible:!!$('volToggle')?.checked})}catch{}const ant=$('antStatus');if(ant)ant.style.display=$('antToggle')?.checked?'':'none';return true}
async function refresh(){if(loading)return;loading=true;try{const tf=window.__QubicChartCore?.timeframe||$('qtf')?.value||$('tf')?.value||'15m';const r=await fetch(`/api/mobile-candles?interval=${encodeURIComponent(tf)}&limit=1000&indicator=1&t=${Date.now()}`,{cache:'no-store'}),j=await r.json();if(r.ok&&j?.ok&&Array.isArray(j.candles)){rows=j.candles.filter(x=>Number.isFinite(+x.time)&&+x.close>0).sort((a,b)=>+a.time-+b.time);paint()}}catch(e){console.warn('indicator refresh',e)}finally{loading=false}}
function save(id,val){try{localStorage.setItem('qIndicator:'+id,String(val))}catch{}}
function restore(id,def){try{const v=localStorage.getItem('qIndicator:'+id);return v==null?def:v==='true'}catch{return def}}
function migrate21(){try{const old=localStorage.getItem('qIndicator:ema21');if(localStorage.getItem('qIndicator:ema20')==null&&old!=null)localStorage.setItem('qIndicator:ema20',old);localStorage.removeItem('qIndicator:ema21')}catch{}}
function bind(){migrate21();for(const p of periods){const box=$(`ema${p}`);if(box){box.checked=restore(`ema${p}`,false);box.addEventListener('change',()=>{save(`ema${p}`,box.checked);if(!paint())refresh()})}const col=document.querySelector(`.emaColor[data-ema="${p}"]`);if(col)col.addEventListener('input',()=>{try{series[p]?.applyOptions({color:col.value})}catch{}})}[['volToggle',true],['cvdToggle',true],['antToggle',true]].forEach(([id,def])=>{const e=$(id);if(e){e.checked=restore(id,def);e.addEventListener('change',()=>{save(id,e.checked);if(!paint())refresh()})}});window.addEventListener('qubic:timeframe',()=>setTimeout(refresh,120));['tf','qtf'].forEach(id=>$(id)?.addEventListener('change',()=>setTimeout(refresh,150)));document.querySelectorAll('#quickTf [data-tf]').forEach(b=>b.addEventListener('click',()=>setTimeout(refresh,170)));let tries=0,constReady=setInterval(()=>{tries++;if(window.__QubicChart){clearInterval(constReady);refresh()}else if(tries>40)clearInterval(constReady)},250);setTimeout(refresh,500);setInterval(()=>{if(!document.hidden)refresh()},15000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
window.__QubicIndicators={refresh,paint,get rows(){return rows.slice()}};
})();