(()=>{
const $=id=>document.getElementById(id);
const periods=[9,20,50,200];
let rows=[],loading=false,hookedSeries=null,subscribed=false,raf=0;
function normalise(a){return (Array.isArray(a)?a:[]).map(x=>({time:+x.time,open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume||0})).filter(x=>Number.isFinite(x.time)&&x.close>0).sort((a,b)=>a.time-b.time)}
function ema(data,p){if(data.length<p)return[];const k=2/(p+1);let v=data.slice(0,p).reduce((s,x)=>s+x.close,0)/p,out=[{time:data[p-1].time,value:v}];for(let i=p;i<data.length;i++){v=data[i].close*k+v*(1-k);out.push({time:data[i].time,value:v})}return out}
function regression(data){if(data.length<20)return{mid:[],up:[],down:[]};const n=Math.min(120,data.length),a=data.slice(-n),sx=n*(n-1)/2,sxx=(n-1)*n*(2*n-1)/6,sy=a.reduce((s,x)=>s+x.close,0),sxy=a.reduce((s,x,i)=>s+i*x.close,0),den=n*sxx-sx*sx;if(!den)return{mid:[],up:[],down:[]};const m=(n*sxy-sx*sy)/den,b=(sy-m*sx)/n,res=a.map((x,i)=>x.close-(b+m*i)),sd=Math.sqrt(res.reduce((s,v)=>s+v*v,0)/Math.max(1,n-2)),mid=a.map((x,i)=>({time:x.time,value:b+m*i}));return{mid,up:mid.map(x=>({time:x.time,value:x.value+2*sd})),down:mid.map(x=>({time:x.time,value:x.value-2*sd}))}}
function overlay(){let host=$('qchart');if(!host)return null;if(getComputedStyle(host).position==='static')host.style.position='relative';let svg=$('indicatorOverlay');if(!svg){svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.id='indicatorOverlay';svg.setAttribute('aria-hidden','true');svg.style.cssText='position:absolute;inset:0;width:100%;height:100%;z-index:8;pointer-events:none;overflow:hidden';host.appendChild(svg)}const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);svg.setAttribute('viewBox',`0 0 ${w} ${h}`);return svg}
function coord(pt){const c=window.__QubicChart,s=window.__QubicCandleSeries,host=$('qchart');if(!c||!s||!host)return null;let x=null,y=null;try{x=c.timeScale().timeToCoordinate(pt.time);y=s.priceToCoordinate(pt.value)}catch{}if(Number.isFinite(x)&&Number.isFinite(y))return{x,y};return null}
function pathFor(data){let d='',started=false;for(const pt of data){const p=coord(pt);if(!p){started=false;continue}d+=(started?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)+' ';started=true}return d.trim()}
function addPath(svg,data,color,width=2,dash=''){const d=pathFor(data);if(!d)return;const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);p.setAttribute('fill','none');p.setAttribute('stroke',color);p.setAttribute('stroke-width',String(width));p.setAttribute('stroke-linejoin','round');p.setAttribute('stroke-linecap','round');p.setAttribute('vector-effect','non-scaling-stroke');if(dash)p.setAttribute('stroke-dasharray',dash);svg.appendChild(p)}
function paintOverlay(){cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const svg=overlay();if(!svg||!rows.length)return;svg.replaceChildren();for(const p of periods){if(!$(`ema${p}`)?.checked)continue;const color=document.querySelector(`.emaColor[data-ema="${p}"]`)?.value||'#ffffff';addPath(svg,ema(rows,p),color,p===200?2.6:2.2)}if($('cvdToggle')?.checked){const r=regression(rows);addPath(svg,r.mid,'#7adff2',2.1);addPath(svg,r.up,'#7adff2',1.2,'5 5');addPath(svg,r.down,'#7adff2',1.2,'5 5')}})}
function paint(){paintOverlay();try{window.__QubicVolumeSeries?.applyOptions({visible:!!$('volToggle')?.checked})}catch{}const ant=$('antStatus');if(ant)ant.style.display=$('antToggle')?.checked?'':'none';return !!rows.length}
function hookCandles(){const s=window.__QubicCandleSeries;if(!s||s===hookedSeries||typeof s.setData!=='function')return false;hookedSeries=s;const native=s.setData.bind(s);s.setData=data=>{rows=normalise(data);const out=native(data);queueMicrotask(paint);return out};return true}
function subscribeChart(){if(subscribed||!window.__QubicChart)return;subscribed=true;try{window.__QubicChart.timeScale().subscribeVisibleTimeRangeChange(()=>paintOverlay())}catch{}addEventListener('resize',paintOverlay,{passive:true})}
async function refresh(){if(loading)return;loading=true;try{hookCandles();subscribeChart();const tf=window.__QubicChartCore?.timeframe||$('qtf')?.value||$('tf')?.value||'15m';const r=await fetch(`/api/mobile-candles?interval=${encodeURIComponent(tf)}&limit=1000&indicator=1&t=${Date.now()}`,{cache:'no-store'}),j=await r.json();if(r.ok&&j?.ok&&Array.isArray(j.candles)){rows=normalise(j.candles);paint()}}catch(e){console.warn('indicator refresh',e)}finally{loading=false}}
function save(id,val){try{localStorage.setItem('qIndicator:'+id,String(val))}catch{}}
function restore(id,def){try{const v=localStorage.getItem('qIndicator:'+id);return v==null?def:v==='true'}catch{return def}}
function migrate21(){try{const old=localStorage.getItem('qIndicator:ema21');if(localStorage.getItem('qIndicator:ema20')==null&&old!=null)localStorage.setItem('qIndicator:ema20',old);localStorage.removeItem('qIndicator:ema21')}catch{}}
function bind(){migrate21();for(const p of periods){const box=$(`ema${p}`);if(box){box.checked=restore(`ema${p}`,false);box.addEventListener('change',()=>{save(`ema${p}`,box.checked);paint()})}const col=document.querySelector(`.emaColor[data-ema="${p}"]`);if(col)col.addEventListener('input',paintOverlay)}[['volToggle',true],['cvdToggle',true],['antToggle',true]].forEach(([id,def])=>{const e=$(id);if(e){e.checked=restore(id,def);e.addEventListener('change',()=>{save(id,e.checked);paint()})}});window.addEventListener('qubic:timeframe',()=>setTimeout(refresh,120));['tf','qtf'].forEach(id=>$(id)?.addEventListener('change',()=>setTimeout(refresh,140)));document.querySelectorAll('#quickTf [data-tf]').forEach(b=>b.addEventListener('click',()=>setTimeout(refresh,160)));let tries=0;const ready=setInterval(()=>{tries++;if(window.__QubicChart&&window.__QubicCandleSeries){hookCandles();subscribeChart();clearInterval(ready);refresh()}else if(tries>120)clearInterval(ready)},100);setTimeout(refresh,600);setInterval(()=>{if(!document.hidden){hookCandles();paintOverlay()}},1000);setInterval(()=>{if(!document.hidden)refresh()},15000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
window.__QubicIndicators={refresh,paint,get rows(){return rows.slice()}};
})();