(()=>{'use strict';
const VERSION='layered-runtime-v6-exact-chart-coordinates';
const $=id=>document.getElementById(id);
const state={chart:false,candles:false,indicators:false,v9:false,avwap:false,bot:false,markers:false,sound:false,lastMarkerCount:0,lastCandleCount:0,lastError:'',updatedAt:0};
let rows=[],audioCtx=null,audioOn=false,lastBotEvent='',lastLiveSound='';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
function bot(){try{return{history:window.QUBIC_PAPER_BOT?.history?.()||read('qPaperTradesV1',[]),open:window.QUBIC_PAPER_BOT?.open?.()||read('qPaperOpenV1',null)}}catch{return{history:[],open:null}}}
function css(){if($('qRuntimeCss'))return;const s=document.createElement('style');s.id='qRuntimeCss';s.textContent=`#predictionPanel,.qUnifiedCard,#runtimeHealth{border:1px solid #223443!important;border-radius:14px!important;background:linear-gradient(180deg,#09121b,#071019)!important;color:#e7eef2}.qUnifiedCard,#runtimeHealth{margin-top:10px;padding:12px 13px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.qCardHead{display:flex;justify-content:space-between;align-items:center;gap:8px}.qCardHead small{display:block;color:#718694;font:800 7px ui-monospace;letter-spacing:.12em}.qCardHead b{display:block;margin-top:3px;font:900 12px ui-monospace}.qCardFoot{margin-top:7px;color:#617684;font:700 7px ui-monospace}.qHealthGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:8px}.qHealthCell{border:1px solid #2a3944;border-radius:7px;padding:6px;text-align:center;font:800 7px ui-monospace}.qHealthCell.on{color:#67ea94;border-color:#24583c;background:#0a1a12}.qHealthCell.off{color:#ff818a;border-color:#57343a;background:#1d0e11}#qchart{position:relative!important}.qBotMarkerLayer{position:absolute;inset:0;z-index:9999;pointer-events:none;overflow:hidden}.qBotBadge{position:absolute;transform:translate(-50%,-50%);padding:5px 7px;min-width:64px;border-radius:8px;color:white;font:1000 8px/1 ui-monospace;text-align:center;white-space:nowrap;box-shadow:0 4px 16px #000c}.qBotBadge.buy{background:#087a43;border:2px solid #55ff9f}.qBotBadge.sell{background:#9b2430;border:2px solid #ff7b85}.qBotBadge.exit{background:#273846;border:2px solid #a5bac5}.qBotBadge:after{content:'';position:absolute;left:50%;width:2px;height:11px;background:currentColor;opacity:.9}.qBotBadge.buy:after{top:-12px}.qBotBadge.sell:after{bottom:-12px}.qBotBadge.exit:after{display:none}@media(max-width:700px){.qBotBadge{font-size:7px;min-width:54px;padding:4px 5px}.qHealthGrid{grid-template-columns:repeat(4,1fr)}}`;document.head.appendChild(s)}
function capture(a){const x=(a||[]).map(c=>({time:+c.time,open:+c.open,high:+c.high,low:+c.low,close:+c.close})).filter(c=>Number.isFinite(c.time)&&c.high>0&&c.low>0).sort((a,b)=>a.time-b.time);if(x.length){rows=x;state.candles=true;state.lastCandleCount=x.length}}
async function seed(){try{const tf=String(window.__QubicChartCore?.timeframe||$('qtf')?.value||$('tf')?.value||'15m');const r=await fetch('/api/mobile-candles?interval='+encodeURIComponent(tf)+'&limit=1000&botMarkers=1&t='+Date.now(),{cache:'no-store'});const j=await r.json();capture(j?.candles||[])}catch(e){state.lastError='candle feed '+e.message}}
function nearest(ms){const x=+ms/1000;if(!Number.isFinite(x)||!rows.length)return null;let best=rows[0],d=Math.abs(best.time-x);for(const c of rows){const n=Math.abs(c.time-x);if(n<d){best=c;d=n}else if(c.time>x&&n>d)break}return best}
function events(){const b=bot(),o=[];for(const t of (b.history||[]).slice(-60)){if(t?.openedAt){const c=nearest(t.openedAt);if(c)o.push({kind:'ENTRY',side:t.side,time:c.time,price:+t.entry||c.close,pnl:0,candle:c})}if(t?.closedAt){const c=nearest(t.closedAt);if(c)o.push({kind:'EXIT',side:t.side,time:c.time,price:+t.exit||c.close,pnl:+t.resultPct||0,candle:c})}}if(b.open?.openedAt){const c=nearest(b.open.openedAt);if(c)o.push({kind:'OPEN',side:b.open.side,time:c.time,price:+b.open.entry||c.close,pnl:0,candle:c})}return o}
function native(ev){const s=window.__QubicCandleSeries;if(!s?.setMarkers)return false;try{s.setMarkers(ev.map(e=>{const buy=String(e.side).toUpperCase()==='BUY',exit=e.kind==='EXIT';return{time:e.time,position:exit?(buy?'aboveBar':'belowBar'):(buy?'belowBar':'aboveBar'),shape:exit?'circle':buy?'arrowUp':'arrowDown',color:exit?(e.pnl>=0?'#36d98b':'#ff6574'):(buy?'#20e68b':'#ff5364'),text:exit?`EXIT ${e.pnl>=0?'+':''}${e.pnl.toFixed(2)}%`:`${e.kind==='OPEN'?'OPEN':'BOT'} ${buy?'BUY':'SELL'}`}}).sort((a,b)=>a.time-b.time));return true}catch(e){state.lastError='native marker '+e.message;return false}}
function layer(){const h=$('qchart');if(!h)return null;let l=h.querySelector('.qBotMarkerLayer');if(!l){l=document.createElement('div');l.className='qBotMarkerLayer';h.appendChild(l)}return l}
function exactCoord(e){try{const c=window.__QubicChart,s=window.__QubicCandleSeries;if(!c||!s)return null;const buy=String(e.side).toUpperCase()==='BUY',exit=e.kind==='EXIT',anchor=exit?e.candle.close:(buy?e.candle.low:e.candle.high),x=c.timeScale().timeToCoordinate(e.time),y=s.priceToCoordinate(anchor);return Number.isFinite(x)&&Number.isFinite(y)?{x,y}:null}catch{return null}}
function pinned(ev){const l=layer();if(!l)return false;l.innerHTML='';let shown=0;for(const e of ev){const p=exactCoord(e);if(!p)continue;const buy=String(e.side).toUpperCase()==='BUY',exit=e.kind==='EXIT',b=document.createElement('div');b.className='qBotBadge '+(exit?'exit':buy?'buy':'sell');b.style.left=p.x+'px';b.style.top=(p.y+(exit?0:buy?16:-16))+'px';b.textContent=exit?`EXIT ${e.pnl>=0?'+':''}${e.pnl.toFixed(2)}%`:`${e.kind==='OPEN'?'OPEN':'BOT'} ${buy?'BUY':'SELL'}`;l.appendChild(b);shown++}return shown>0}
function draw(){const ev=events();state.lastMarkerCount=ev.length;const hasChart=!!(window.__QubicChart&&window.__QubicCandleSeries),n=native(ev),p=pinned(ev);state.chart=hasChart;state.markers=ev.length===0?hasChart:(n||p);if(!hasChart)state.lastError='exact chart API not captured';else if(ev.length&&!state.markers)state.lastError='trade events outside visible chart range';else state.lastError='';paint();return state.markers}
function healthEl(){let e=$('runtimeHealth');if(e)return e;const h=$('paperBotPanel')||$('predictionPanel')||$('qp');if(!h)return null;e=document.createElement('section');e.id='runtimeHealth';e.className='qUnifiedCard';h.insertAdjacentElement('afterend',e);return e}
function paint(){const e=healthEl();if(!e)return;state.chart=!!(window.__QubicChart&&window.__QubicCandleSeries);state.indicators=!!window.__QubicIndicators?.status?.ready;state.v9=!!window.QUBIC_PAPER_SIGNAL||!!window.QUBIC_PAPER_BOT;state.avwap=!!window.QUBIC_AVWAP?.ok;state.bot=!!window.QUBIC_PAPER_BOT;state.sound=audioOn&&audioCtx?.state==='running';const a=[['CHART',state.chart],['CANDLES',state.candles],['INDICATORS',state.indicators],['V9',state.v9],['AVWAP',state.avwap],['BOT',state.bot],['MARKERS',state.markers],['SOUND',state.sound]];e.innerHTML=`<div class="qCardHead"><div><small>RUNTIME STATUS</small><b>SYSTEM LAYERS</b></div><span class="qCardFoot">${VERSION}</span></div><div class="qHealthGrid">${a.map(([n,on])=>`<div class="qHealthCell ${on?'on':'off'}">${on?'●':'○'} ${n}</div>`).join('')}</div><div class="qCardFoot">Candles ${state.lastCandleCount} · Bot events ${state.lastMarkerCount}${state.lastError?' · '+state.lastError:''}</div>`}
async function ensureAudio(){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return false;if(!audioCtx||audioCtx.state==='closed')audioCtx=new A({latencyHint:'interactive'});if(audioCtx.state==='suspended')await audioCtx.resume();return audioCtx.state==='running'}catch{return false}}
function beep(side='buy',strong=false){if(!audioOn||audioCtx?.state!=='running')return;try{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=side==='sell'?240:650;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(strong?.08:.035,audioCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.18);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.2)}catch{}}
function soundUI(){const b=$('audio'),t=$('soundBtn'),on=audioOn&&audioCtx?.state==='running';if(b)b.textContent=on?'🔊 TRADE SOUND ON':'🔇 ENABLE TRADE SOUND';if(t)t.textContent=(on?'🔊':'🔈')+' Sound $5 – $1M⌄'}
async function toggle(e){e?.preventDefault?.();audioOn=!audioOn;if(audioOn&&await ensureAudio())beep('buy',true);soundUI();paint()}
function bindSound(){if($('audio'))$('audio').onclick=toggle;const t=$('soundBtn'),m=$('soundMenu');if(t&&m)t.onclick=e=>{e.preventDefault();m.classList.toggle('open')};soundUI()}
function botSound(){if(!audioOn)return;const b=bot(),last=b.history?.at?.(-1),k=b.open?.id?'O:'+b.open.id:last?.id?'C:'+last.id+':'+last.closedAt:'';if(k&&k!==lastBotEvent){if(lastBotEvent)beep(String(b.open?.side||last?.side||'BUY').toLowerCase(),true);lastBotEvent=k}}
async function liveSound(){if(!audioOn||document.hidden)return;try{const r=await fetch('/api/live-trades?sound=1&t='+Date.now(),{cache:'no-store'}),j=await r.json(),x=(j?.trades||[]).filter(t=>+t.t>Date.now()-15000).sort((a,b)=>+b.t-+a.t)[0];if(!x)return;const usd=(+x.p||0)*(+x.q||0),k=[x.ex,x.t,x.p,x.q,x.s].join('|');if(usd>=5&&k!==lastLiveSound){lastLiveSound=k;beep(String(x.s).toLowerCase()==='sell'?'sell':'buy')}}catch{}}
async function refresh(force=false){if(force||!rows.length)await seed();draw();botSound();paint()}
css();bindSound();window.addEventListener('qubic:chart-series',()=>setTimeout(()=>refresh(true),30));window.addEventListener('qubic:timeframe',()=>{rows=[];setTimeout(()=>refresh(true),150)});window.addEventListener('paperbot:open',()=>setTimeout(()=>{draw();botSound()},20));window.addEventListener('paperbot:close',()=>setTimeout(()=>{draw();botSound()},20));window.addEventListener('resize',()=>setTimeout(draw,80));document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true)});setInterval(()=>refresh(false),1000);setInterval(liveSound,5000);setTimeout(()=>refresh(true),300);window.QUBIC_RUNTIME={version:VERSION,state,refresh:()=>refresh(true),draw,beep};
})();