(()=>{'use strict';
const VERSION='layered-runtime-v2-direct-series';
const $=id=>document.getElementById(id);
const state={chart:false,candles:false,indicators:false,v9:false,avwap:false,bot:false,markers:false,sound:false,lastMarkerCount:0,lastCandleCount:0,lastError:'',updatedAt:0};
let candleTimes=[],patchedSeries=null,audioCtx=null,audioOn=false,lastBotEvent='',lastLiveSound='';
function tf(){return String(window.__QubicChartCore?.timeframe||$('qtf')?.value||$('tf')?.value||'15m')}
function readBot(){try{return{history:window.QUBIC_PAPER_BOT?.history?.()||JSON.parse(localStorage.getItem('qPaperTradesV1')||'[]'),open:window.QUBIC_PAPER_BOT?.open?.()||JSON.parse(localStorage.getItem('qPaperOpenV1')||'null')}}catch{return{history:[],open:null}}}
function captureTimes(rows){const a=(rows||[]).map(x=>+x.time).filter(Number.isFinite).sort((a,b)=>a-b);if(a.length){candleTimes=[...new Set(a)];state.candles=true;state.lastCandleCount=candleTimes.length}}
function nearest(ms){const x=+ms/1000;if(!Number.isFinite(x)||!candleTimes.length)return null;let best=candleTimes[0],d=Math.abs(best-x);for(const t of candleTimes){const nd=Math.abs(t-x);if(nd<d){best=t;d=nd}else if(t>x&&nd>d)break}return best}
function events(){const {history,open}=readBot(),out=[];for(const t of (history||[]).slice(-100)){if(t?.openedAt)out.push({kind:'ENTRY',side:t.side,time:nearest(t.openedAt),pnl:0});if(t?.closedAt)out.push({kind:'EXIT',side:t.side,time:nearest(t.closedAt),pnl:+t.resultPct||0})}if(open?.openedAt)out.push({kind:'OPEN',side:open.side,time:nearest(open.openedAt),pnl:0});return out.filter(x=>Number.isFinite(x.time))}
function draw(){const s=window.__QubicCandleSeries;if(!s||typeof s.setMarkers!=='function'||!candleTimes.length){state.markers=false;return false}const ev=events();const markers=ev.map(e=>{const buy=String(e.side).toUpperCase()==='BUY',exit=e.kind==='EXIT',good=e.pnl>=0;return{time:e.time,position:exit?(buy?'aboveBar':'belowBar'):(buy?'belowBar':'aboveBar'),color:exit?(good?'#36d98b':'#ff6574'):(buy?'#20e68b':'#ff5364'),shape:exit?'circle':buy?'arrowUp':'arrowDown',text:exit?`EXIT ${good?'+':''}${e.pnl.toFixed(2)}%`:`${e.kind==='OPEN'?'OPEN':'BOT'} ${buy?'BUY':'SELL'}`,size:2}}).sort((a,b)=>a.time-b.time);try{s.setMarkers(markers);state.markers=true;state.lastMarkerCount=markers.length;state.lastError='';window.__QubicDirectBotMarkers=markers;return true}catch(e){state.markers=false;state.lastError='marker draw: '+e.message;return false}}
function patchSeries(){const s=window.__QubicCandleSeries;if(!s||s===patchedSeries)return false;patchedSeries=s;const original=s.setData?.bind(s);if(original&&!s.__botMarkerWrapped){s.setData=rows=>{const r=original(rows);captureTimes(rows);queueMicrotask(draw);return r};s.__botMarkerWrapped=true}state.chart=true;return true}
async function seedTimes(){try{const r=await fetch('/api/mobile-candles?interval='+encodeURIComponent(tf())+'&limit=1000&markerCore=1&t='+Date.now(),{cache:'no-store'}),j=await r.json();captureTimes(j?.candles||[]);draw()}catch(e){state.lastError='marker candles: '+e.message}}
function ensureHealth(){let el=$('runtimeHealth');if(el)return el;const host=$('predictionPanel')||$('qp');if(!host)return null;el=document.createElement('div');el.id='runtimeHealth';el.style.cssText='margin:9px 0;border:1px solid #233544;border-radius:10px;padding:9px 10px;background:#071018;color:#d9e6ec;font-family:ui-monospace,SFMono-Regular,Menlo,monospace';host.insertAdjacentElement('afterend',el);return el}
function paint(){const el=ensureHealth();if(!el)return;state.chart=!!window.__QubicCandleSeries;state.indicators=!!window.__QubicIndicators?.status?.ready;state.v9=!!window.QUBIC_PAPER_BOT;state.avwap=!!window.QUBIC_AVWAP?.ok;state.bot=!!window.QUBIC_PAPER_BOT;state.sound=audioOn&&audioCtx?.state==='running';const cells=[['CHART',state.chart],['CANDLES',state.candles],['INDICATORS',state.indicators],['V9',state.v9],['AVWAP',state.avwap],['BOT',state.bot],['MARKERS',state.markers],['SOUND',state.sound]];el.innerHTML='<div style="display:flex;justify-content:space-between;gap:8px"><b style="font-size:9px">SYSTEM LAYERS</b><span style="font-size:7px;color:#78909c">'+VERSION+'</span></div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:7px">'+cells.map(([n,on])=>`<div style="border:1px solid ${on?'#24583c':'#493039'};border-radius:6px;padding:5px;text-align:center;font-size:7px;color:${on?'#66ee9b':'#ff8390'}">${on?'●':'○'} ${n}</div>`).join('')+'</div><div style="margin-top:6px;font-size:7px;color:#78909c">Candles '+state.lastCandleCount+' · Bot markers '+state.lastMarkerCount+(state.lastError?' · '+state.lastError:'')+'</div>'}
async function ensureAudio(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;if(!audioCtx||audioCtx.state==='closed')audioCtx=new AC({latencyHint:'interactive'});if(audioCtx.state==='suspended')await audioCtx.resume();return audioCtx.state==='running'}catch{return false}}
function beep(side='buy',strong=false){if(!audioOn||audioCtx?.state!=='running')return;try{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=side==='sell'?230:620;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(strong?.08:.035,audioCtx.currentTime+.012);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.18);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.2)}catch{}}
function setSoundUi(){const b=$('audio'),top=$('soundBtn'),on=audioOn&&audioCtx?.state==='running';if(b)b.textContent=on?'🔊 TRADE SOUND ON':'🔇 ENABLE TRADE SOUND';if(top)top.textContent=(on?'🔊':'🔈')+' Sound $5 – $1M⌄'}
async function toggleSound(e){e?.preventDefault?.();audioOn=!audioOn;if(audioOn){const ok=await ensureAudio();if(ok)beep('buy',true)}setSoundUi();paint()}
function bindSound(){const b=$('audio');if(b)b.onclick=toggleSound;const top=$('soundBtn'),menu=$('soundMenu');if(top&&menu)top.onclick=e=>{e.preventDefault();menu.classList.toggle('open')};setSoundUi()}
function botSound(){if(!audioOn)return;const {history,open}=readBot(),last=history?.at?.(-1),k=open?.id?('O:'+open.id):last?.id?('C:'+last.id+':'+last.closedAt):'';if(k&&k!==lastBotEvent){if(lastBotEvent)beep(String(open?.side||last?.side||'BUY').toLowerCase(),true);lastBotEvent=k}}
async function liveSound(){if(!audioOn||document.hidden)return;try{const r=await fetch('/api/live-trades?soundCore=1&t='+Date.now(),{cache:'no-store'}),j=await r.json(),x=(j?.trades||[]).filter(t=>+t.t>Date.now()-15000).sort((a,b)=>+b.t-+a.t)[0];if(!x)return;const usd=(+x.p||0)*(+x.q||0),k=[x.ex,x.t,x.p,x.q,x.s].join('|');if(usd>=5&&k!==lastLiveSound){lastLiveSound=k;beep(String(x.s).toLowerCase()==='sell'?'sell':'buy')}}catch{}}
async function refresh(force=false){patchSeries();if(force||!candleTimes.length)await seedTimes();draw();botSound();paint()}
window.addEventListener('qubic:chart-series',()=>setTimeout(()=>refresh(true),50));window.addEventListener('qubic:timeframe',()=>{candleTimes=[];setTimeout(()=>refresh(true),150)});document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true)});bindSound();setInterval(()=>refresh(false),1000);setInterval(liveSound,5000);setTimeout(()=>refresh(true),250);window.QUBIC_RUNTIME={version:VERSION,state,refresh:()=>refresh(true),beep,draw};
})();