(()=>{
const $=id=>document.getElementById(id), clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const money=v=>{let a=Math.abs(v);return (v<0?'−':v>0?'+':'')+(a>=1e6?'$'+(a/1e6).toFixed(2)+'M':a>=1e3?'$'+(a/1e3).toFixed(1)+'K':'$'+Math.round(a))};
let book=null,lastBook=0,busy=false,tradeBusy=false,lastTradePull=0;
function trades(){try{return typeof R!=='undefined'?R:[]}catch{return[]}}
async function recoverTrades(){if(tradeBusy||Date.now()-lastTradePull<2500)return;tradeBusy=true;try{let r=await fetch('/api/live-trades?nf='+Date.now(),{cache:'no-store'}),x=await r.json();if(!r.ok||!x.ok)throw Error(r.status);(x.trades||[]).forEach(t=>{try{add(t.ex,t.p,t.q,t.s,t.t,t.id||('proxy-'+t.ex+'-'+t.t+'-'+t.p+'-'+t.q))}catch{}});lastTradePull=Date.now();try{Object.entries(x.status||{}).forEach(([k,v])=>{if(v&&typeof feed!=='undefined'&&k in feed)feed[k]=1;if(v&&typeof exCard==='function')exCard(k,'LIVE')});stats();render()}catch{}}catch(e){console.warn('flow recovery',e)}finally{tradeBusy=false}}
async function getBook(){if(busy||Date.now()-lastBook<5000)return;busy=true;try{let r=await fetch('/api/orderbook?nf='+Date.now(),{cache:'no-store'}),x=await r.json();if(r.ok&&x.ok){book=x;lastBook=Date.now()}}catch{}finally{busy=false}}
function calc(){let now=Date.now(),a=trades().filter(x=>x&&x.t&&now-x.t>=0&&now-x.t<300000&&+x.usd>0&&(x.s==='buy'||x.s==='sell'));
 let weighted=0,wabs=0,rawBuy=0,rawSell=0,whaleBuy=0,whaleSell=0,by={};
 a.forEach(x=>{let age=(now-x.t)/1000,rec=Math.exp(-age/95),size=clamp(Math.log10(Math.max(10,+x.usd))/4,.35,1.35),sg=x.s==='buy'?1:-1,w=(+x.usd)*rec*size;weighted+=sg*w;wabs+=Math.abs(w);if(sg>0)rawBuy+=+x.usd;else rawSell+=+x.usd;if(+x.usd>=5000){if(sg>0)whaleBuy+=+x.usd;else whaleSell+=+x.usd}let e=by[x.ex]||(by[x.ex]={b:0,s:0});sg>0?e.b+=+x.usd:e.s+=+x.usd});
 let exec=wabs?weighted/wabs:0,venue=Object.entries(by).map(([n,v])=>({n,v:(v.b-v.s)/Math.max(1,v.b+v.s),vol:v.b+v.s})).filter(x=>x.vol>0),pos=venue.filter(x=>x.v>.08).length,neg=venue.filter(x=>x.v<-.08).length,agree=venue.length?Math.max(pos,neg)/venue.length:0,venueDir=pos>neg?1:neg>pos?-1:0;
 let books=(book?.books||[]),ob=books.length?books.reduce((s,b)=>s+clamp(+b.imbalance||0,-1,1),0)/books.length:0,whale=(whaleBuy-whaleSell)/Math.max(1,whaleBuy+whaleSell);
 let mpi=clamp(100*(.35*exec+.30*ob+.20*whale+.15*venueDir*agree),-100,100),conf=clamp(35+Math.abs(mpi)*.45+agree*18+(books.length>=3?8:0),35,92),label=mpi>=60?'STRONG ACCUMULATION':mpi>=25?'ACCUMULATION':mpi<=-60?'STRONG DISTRIBUTION':mpi<=-25?'DISTRIBUTION':'BALANCED / MIXED';
 return{a,rawBuy,rawSell,exec,ob,whale,whaleBuy,whaleSell,venue,agree,mpi,conf,label,books:books.length};}
function build(){let anchor=$('buySellDonut')?.closest('.panel');if(!anchor||$('smartFlow'))return;let p=document.createElement('section');p.id='smartFlow';p.className='panel smartFlow';p.innerHTML='<div class="panelTitle"><b>SMART NET FLOW</b><span>LIVE · 5M WEIGHTED</span></div><div class="mpiHero"><div><small>MARKET PRESSURE INDEX</small><strong id="mpiScore">0</strong><em id="mpiLabel">CALIBRATING</em></div><div><small>CONFIDENCE</small><strong id="mpiConfidence">—</strong><em id="mpiSources">WAITING FOR SOURCES</em></div></div><div class="mpiBar"><i id="mpiBar"></i><b id="mpiMarker"></b></div><div class="flowV2Grid"><div><small>EXECUTED FLOW</small><b id="nfExecuted">—</b></div><div><small>ORDER BOOK</small><b id="nfBook">—</b></div><div><small>WHALE FLOW ≥$5K</small><b id="nfWhale">—</b></div><div><small>EXCHANGE AGREEMENT</small><b id="nfAgree">—</b></div></div><div class="venueFlow" id="nfVenues"></div><p class="nfNote">MPI combines executed trade flow 35%, order-book pressure 30%, large-trade flow 20% and cross-exchange agreement 15%. Executed trades are weighted by size and recency.</p>';anchor.insertAdjacentElement('afterend',p);let s=document.createElement('style');s.textContent='.smartFlow{grid-column:span 1}.mpiHero{display:grid;grid-template-columns:1.3fr .7fr;gap:8px;margin:10px 0}.mpiHero>div,.flowV2Grid>div{border:1px solid #223240;background:#09121b;border-radius:9px;padding:10px}.mpiHero small,.flowV2Grid small{display:block;color:#738798;font-size:7px}.mpiHero strong{display:block;font-size:23px;margin-top:3px}.mpiHero em{display:block;color:#9bafbc;font-size:8px;font-style:normal;margin-top:3px}.mpiBar{height:12px;border-radius:8px;background:linear-gradient(90deg,#ff5058,#263746 50%,#4ee06b);position:relative;margin:10px 2px 12px}.mpiBar b{position:absolute;top:-4px;width:3px;height:20px;background:#fff;border-radius:2px;box-shadow:0 0 8px #fff}.flowV2Grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.flowV2Grid b{display:block;margin-top:4px;font-size:11px}.venueFlow{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.venueFlow span{font-size:7px;padding:5px 7px;border:1px solid #263746;border-radius:12px}.venueFlow .buy{color:#55ee7c;border-color:#245b35}.venueFlow .sell{color:#ff6870;border-color:#633038}.nfNote{color:#607483;font-size:7px;line-height:1.45;margin:9px 0 0}@media(max-width:700px){.mpiHero{grid-template-columns:1fr 1fr}.mpiHero strong{font-size:19px}}';document.head.appendChild(s)}
function paint(){let m=calc(),green='#55ee7c',red='#ff626b',neutral='#d4e0e7',c=m.mpi>8?green:m.mpi<-8?red:neutral;let set=(id,v,col)=>{let e=$(id);if(e){e.textContent=v;if(col)e.style.color=col}};set('mpiScore',(m.mpi>=0?'+':'')+m.mpi.toFixed(0),c);set('mpiLabel',m.label,c);set('mpiConfidence',m.conf.toFixed(0)+'%',c);set('mpiSources',`${m.venue.length} TRADE VENUES · ${m.books} BOOKS`);set('nfExecuted',(m.exec>=0?'+':'')+(m.exec*100).toFixed(0)+'%',m.exec>0?green:m.exec<0?red:neutral);set('nfBook',(m.ob>=0?'+':'')+(m.ob*100).toFixed(0)+'%',m.ob>0?green:m.ob<0?red:neutral);set('nfWhale',money(m.whaleBuy-m.whaleSell),m.whale>0?green:m.whale<0?red:neutral);set('nfAgree',Math.round(m.agree*100)+'%');let mark=$('mpiMarker');if(mark)mark.style.left=`calc(${clamp((m.mpi+100)/2,0,100)}% - 1px)`;let v=$('nfVenues');if(v)v.innerHTML=m.venue.sort((a,b)=>b.vol-a.vol).map(x=>`<span class="${x.v>.08?'buy':x.v<-.08?'sell':''}">${x.n} ${x.v>.08?'▲':x.v<-.08?'▼':'•'} ${Math.abs(x.v*100).toFixed(0)}%</span>`).join('');
 let weightedDollar=(m.rawBuy+m.rawSell)*m.exec;set('netDelta',money(weightedDollar),m.exec>0?green:m.exec<0?red:neutral);set('qc',money(weightedDollar),m.exec>0?green:m.exec<0?red:neutral);set('donutNet',money(weightedDollar),m.exec>0?green:m.exec<0?red:neutral);
 window.QUBIC_NET_FLOW={...m,ts:Date.now()};}
build();recoverTrades();getBook();paint();setInterval(()=>{recoverTrades();getBook();paint()},1500);
})();