(()=>{
const $=id=>document.getElementById(id),qa=s=>[...document.querySelectorAll(s)];
function closeMenus(except=null){qa('.floatingMenu').forEach(m=>{if(m!==except)m.classList.remove('open')})}
function repairBrand(){qa('.officialBrand').forEach((b,i)=>{b.innerHTML=`<img class="officialQubicLogo" src="/qubic-logo-white.svg" alt="Qubic"><small class="officialSub">${i===0?'LIVE CHART':'LIVE CHART · unofficial analytics interface'}</small>`})}
function addClose(m){if(!m||m.querySelector('.restoreClose'))return;const b=document.createElement('button');b.type='button';b.className='restoreClose';b.setAttribute('aria-label','Close');b.textContent='×';b.onclick=e=>{e.preventDefault();e.stopPropagation();m.classList.remove('open')};m.appendChild(b)}
function bindMenus(){[['indBtn','indMenu'],['marketsBtn','marketsMenu'],['soundBtn','soundMenu'],['rangeBtn','rangeMenu']].forEach(([bid,mid])=>{const b=$(bid),m=$(mid);if(!b||!m)return;addClose(m);b.onclick=e=>{e.preventDefault();e.stopPropagation();const willOpen=!m.classList.contains('open');closeMenus();m.classList.toggle('open',willOpen)}});document.addEventListener('click',e=>{if(!e.target.closest('.floatingMenu')&&!e.target.closest('#indBtn')&&!e.target.closest('#marketsBtn')&&!e.target.closest('#soundBtn')&&!e.target.closest('#rangeBtn'))closeMenus()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenus()});closeMenus()}
async function marketStatus(){try{const r=await fetch('/api/live-trades?ui-status=1&t='+Date.now(),{cache:'no-store'});if(!r.ok)return;const j=await r.json();const st=j.status||{};const names=Object.keys(st);if($('marketCount'))$('marketCount').textContent=names.length||'—';const board=$('exchangeBoard');if(board){board.innerHTML=names.map(n=>`<div class="exCard"><b><span>${n.toUpperCase()}</span><span class="exState ${st[n]?'live':''}">${st[n]?'● LIVE':'● RETRY'}</span></b><small>QUBIC / USDT</small></div>`).join('')||'<div class="empty">Waiting for market sources…</div>'}}catch{}}
function loadScript(src,key){if(document.querySelector(`script[data-${key}]`))return;const s=document.createElement('script');s.src=src;s.setAttribute(`data-${key}`,'1');document.body.appendChild(s)}
function loadControls(){loadScript('/original-controls.js?v=3','original-controls');loadScript('/precision-fixes.js?v=1','precision-fixes');loadScript('/pattern-intelligence.js?v=1','pattern-intelligence')}
const css=document.createElement('style');css.textContent=`
.officialBrand{display:flex!important;align-items:center!important;gap:10px!important}.officialQubicLogo{width:126px!important;height:auto!important;display:block!important;object-fit:contain!important}.officialBrand.mini .officialQubicLogo{width:104px!important}.officialSub{display:block!important;color:#8b989f!important;font:800 7px ui-monospace!important;letter-spacing:.18em!important;white-space:nowrap!important}
.floatingMenu{position:fixed!important;z-index:300!important;display:none!important;background:#0b1118f5!important;backdrop-filter:blur(16px)!important;-webkit-backdrop-filter:blur(16px)!important;border:1px solid #35444f!important;border-radius:9px!important;box-shadow:0 18px 55px #000d!important;padding:42px 11px 11px!important;max-height:min(70vh,540px);overflow:auto}.floatingMenu.open{display:grid!important;gap:8px!important}.floatingMenu .menuHead{position:absolute;left:11px;right:48px;top:10px}.restoreClose{position:absolute!important;right:8px!important;top:7px!important;width:32px!important;min-width:32px!important;height:32px!important;min-height:32px!important;padding:0!important;border:1px solid #3a4b58!important;border-radius:50%!important;background:#111b24!important;color:#fff!important;font:700 20px/28px system-ui!important;z-index:5!important}
#marketsMenu{top:82px!important;left:50%!important;right:auto!important;transform:translateX(-50%)!important;width:340px!important}#indMenu{top:82px!important}#soundMenu{top:82px!important}.exCard{min-height:52px}.exState.live{color:#4ee06b!important}
@media(max-width:800px){.officialQubicLogo{width:118px!important}.officialBrand.mini .officialQubicLogo{width:96px!important}.topbar .officialBrand{width:100%;margin-bottom:2px}.floatingMenu{top:118px!important;left:12px!important;right:12px!important;transform:none!important;width:auto!important;max-height:58vh!important}.floatingMenu.rangeMenu{position:fixed!important;bottom:auto!important}#exchangeBoard{grid-template-columns:1fr 1fr!important}.restoreClose{position:absolute!important}.chartPanel{margin-top:10px!important}}
`;document.head.appendChild(css);
function init(){repairBrand();setTimeout(bindMenus,0);loadControls();marketStatus();setInterval(()=>{if(!document.hidden)marketStatus()},15000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();