(()=>{
  let cfg={mode:'auto',period:200,sdBars:2000,multi:2};
  try{cfg={...cfg,...JSON.parse(localStorage.getItem('sdclrdSettings')||'{}')}}catch{}
  let top,middle,bottom,enabled=true,lastSig='';
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function autoSettings(){const sec=(typeof TF!=='undefined'&&TF[tf])||900,available=B?.size||0;let period,sdBars,multi;if(sec<=30)[period,sdBars,multi]=[120,720,2.4];else if(sec<=60)[period,sdBars,multi]=[150,1000,2.3];else if(sec<=300)[period,sdBars,multi]=[180,1400,2.2];else if(sec<=900)[period,sdBars,multi]=[200,1800,2.1];else if(sec<=3600)[period,sdBars,multi]=[200,2000,2];else if(sec<=14400)[period,sdBars,multi]=[160,1400,1.9];else if(sec<=86400)[period,sdBars,multi]=[120,900,1.8];else[period,sdBars,multi]=[80,600,1.7];if(available){period=clamp(Math.min(period,Math.max(20,Math.floor(available*.32))),20,500);const usable=Math.max(20,available-period);sdBars=Math.max(20,Math.min(sdBars,usable))}return{period,sdBars,multi}}
  function active(){return cfg.mode==='auto'?autoSettings():{period:clamp(Math.round(+cfg.period||200),20,500),sdBars:clamp(Math.round(+cfg.sdBars||2000),20,5000),multi:clamp(+cfg.multi||2,.1,10)}}
  function ensure(){if(top)return;const common={lineWidth:2,lastValueVisible:false,priceLineVisible:false,crosshairMarkerVisible:false};top=chart.addLineSeries({...common,color:'rgba(38,132,255,.9)'});middle=chart.addLineSeries({...common,lineWidth:1,color:'rgba(38,132,255,.44)'});bottom=chart.addLineSeries({...common,color:'rgba(38,132,255,.9)'})}
  function regression(vals,len){const out=new Array(vals.length).fill(NaN),n=len,sx=(n-1)*n/2,sxx=(n-1)*n*(2*n-1)/6,den=n*sxx-sx*sx;let sy=0,sxy=0;for(let i=0;i<vals.length;i++){const y=vals[i];if(i<n){sy+=y;sxy+=i*y;if(i===n-1){const slope=den?(n*sxy-sx*sy)/den:0;out[i]=(sy-slope*sx)/n+slope*(n-1)}}else{const old=vals[i-n],oldSy=sy;sy=oldSy-old+y;sxy=sxy-(oldSy-old)+(n-1)*y;const slope=den?(n*sxy-sx*sy)/den:0;out[i]=(sy-slope*sx)/n+slope*(n-1)}}return out}
  function calculate(){ensure();const S=active(),d=[...B.values()].sort((a,b)=>a.time-b.time);updateStatus(S,d.length);if(d.length<S.period+2){top.setData([]);middle.setData([]);bottom.setData([]);return}const vals=d.map(x=>(x.high+x.low+x.close)/3),regs=regression(vals,S.period),dist=new Array(d.length).fill(NaN);for(let i=S.period-1;i<d.length;i++){const r=regs[i];if(Number.isFinite(r)&&r!==0)dist[i]=Math.abs((vals[i]-r)/r*100)}const T=[],M=[],L=[];let sum=0,sumSq=0,count=0;const queue=[];for(let i=S.period-1;i<d.length;i++){const v=dist[i];if(Number.isFinite(v)){queue.push(v);sum+=v;sumSq+=v*v;count++}else queue.push(null);if(queue.length>S.sdBars){const old=queue.shift();if(old!=null){sum-=old;sumSq-=old*old;count--}}if(i<S.period||count<Math.min(20,S.sdBars))continue;const prior=regs[i-1];if(!Number.isFinite(prior))continue;const mean=sum/count,variance=Math.max(0,sumSq/count-mean*mean),sd=Math.sqrt(variance),pad=sd*S.multi/100;T.push({time:d[i].time,value:prior*(1+pad)});M.push({time:d[i].time,value:prior});L.push({time:d[i].time,value:prior*(1-pad)})}top.setData(T);middle.setData(M);bottom.setData(L);[top,middle,bottom].forEach(s=>s.applyOptions({visible:enabled}))}
  function refresh(force=false){const d=[...B.values()],S=active(),last=d.length?Math.max(...d.slice(-3).map(x=>+x.time||0)):0,sig=last+'|'+d.length+'|'+tf+'|'+cfg.mode+'|'+S.period+'|'+S.sdBars+'|'+S.multi;if(force||sig!==lastSig){lastSig=sig;calculate()}}
  function setVisible(v){enabled=!!v;ensure();[top,middle,bottom].forEach(s=>s.applyOptions({visible:enabled}));if(enabled)refresh(true)}
  function save(){try{localStorage.setItem('sdclrdSettings',JSON.stringify(cfg))}catch{}refresh(true)}
  function updateStatus(S,n){const e=document.getElementById('sdStatus');if(e)e.textContent=(cfg.mode==='auto'?'AUTO':'MANUAL')+' · REG '+S.period+' · SD '+S.sdBars+' · ×'+(+S.multi).toFixed(2)+' · '+n+' bars'}
  function addControls(label){if(document.getElementById('sdControls'))return;const wrap=document.createElement('div');wrap.id='sdControls';wrap.innerHTML='<div class="sdMode"><button id="sdAuto" type="button">AUTO</button><button id="sdManual" type="button">MANUAL</button></div><small id="sdStatus"></small><div class="sdAdjust"><label><span>REG PERIOD</span><div><button data-id="sdPeriod" data-d="-10">−</button><input id="sdPeriod" type="number" min="20" max="500" step="1"><button data-id="sdPeriod" data-d="10">+</button></div></label><label><span>SD BARS</span><div><button data-id="sdBars" data-d="-100">−</button><input id="sdBars" type="number" min="20" max="5000" step="10"><button data-id="sdBars" data-d="100">+</button></div></label><label><span>WIDTH ×</span><div><button data-id="sdMulti" data-d="-0.1">−</button><input id="sdMulti" type="number" min="0.1" max="10" step="0.1"><button data-id="sdMulti" data-d="0.1">+</button></div></label></div><div class="sdPresets"><button data-p="fast">TIGHT</button><button data-p="normal">NORMAL</button><button data-p="wide">WIDE</button><button id="sdReset" type="button">RESET</button></div>';label.insertAdjacentElement('afterend',wrap);const P=document.getElementById('sdPeriod'),D=document.getElementById('sdBars'),M=document.getElementById('sdMulti');const sync=()=>{P.value=cfg.period;D.value=cfg.sdBars;M.value=cfg.multi};sync();function paintMode(){const auto=cfg.mode==='auto';document.getElementById('sdAuto').classList.toggle('active',auto);document.getElementById('sdManual').classList.toggle('active',!auto);wrap.classList.toggle('manual',!auto);[P,D,M].forEach(x=>x.disabled=auto)}paintMode();document.getElementById('sdAuto').onclick=()=>{cfg.mode='auto';paintMode();save()};document.getElementById('sdManual').onclick=()=>{cfg.mode='manual';const a=autoSettings();cfg={...cfg,...a,mode:'manual'};sync();paintMode();save()};const change=(id,val)=>{if(id==='sdPeriod')cfg.period=clamp(Math.round(val),20,500);if(id==='sdBars')cfg.sdBars=clamp(Math.round(val),20,5000);if(id==='sdMulti')cfg.multi=clamp(Math.round(val*10)/10,.1,10);sync();save()};P.oninput=()=>change('sdPeriod',+P.value||200);D.oninput=()=>change('sdBars',+D.value||2000);M.oninput=()=>change('sdMulti',+M.value||2);wrap.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{const id=b.dataset.id,x=document.getElementById(id);change(id,(+x.value||0)+(+b.dataset.d))});wrap.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{cfg.mode='manual';const p=b.dataset.p==='fast'?{period:80,sdBars:600,multi:1.5}:b.dataset.p==='wide'?{period:200,sdBars:1800,multi:3}:{period:150,sdBars:1200,multi:2};cfg={...cfg,...p};sync();paintMode();save()});document.getElementById('sdReset').onclick=()=>{cfg={mode:'auto',period:200,sdBars:2000,multi:2};sync();paintMode();save()}}
  function injectStyle(){if(document.getElementById('sdUiStyle'))return;const s=document.createElement('style');s.id='sdUiStyle';s.textContent='#indMenu{max-height:min(82vh,700px);overflow:auto}#sdControls{border-top:1px solid #ffffff14;margin-top:7px;padding-top:9px;display:grid;gap:8px;font:800 8px ui-monospace}#sdStatus{color:#58d8ff;line-height:1.4}.sdMode,.sdPresets{display:grid;grid-template-columns:repeat(2,1fr);gap:5px}.sdMode button,.sdPresets button{min-height:34px;padding:5px}.sdMode button.active{border-color:#39c655;color:#6bec81;background:#102a18}.sdAdjust{display:grid;gap:6px}.sdAdjust>label{display:grid!important;grid-template-columns:70px 1fr!important;gap:6px!important;align-items:center!important;padding:0!important;border:0!important}.sdAdjust>label>span{color:#a8b4bb}.sdAdjust>label>div{display:grid;grid-template-columns:36px 1fr 36px;gap:4px}.sdAdjust input{width:100%;min-width:0;min-height:36px;text-align:center;padding:4px}.sdAdjust button{min-width:0;min-height:36px;padding:2px;font-size:17px}.sdAdjust input:disabled,.sdAdjust button:has(+ input:disabled),.sdAdjust input:disabled + button{opacity:.35}.sdPresets{grid-template-columns:repeat(4,1fr)}.sdPresets button{font-size:7px}.sdPresets button:not(#sdReset){border-color:#24506a;color:#70dfff}@media(max-width:800px){#indMenu{position:fixed!important;left:8px!important;right:8px!important;top:8px!important;bottom:8px!important;width:auto!important;max-height:none!important;transform:none!important;padding:12px!important;overflow:auto!important}.sdAdjust>label{grid-template-columns:78px 1fr!important}.sdAdjust>label>div{grid-template-columns:42px 1fr 42px}.sdAdjust input,.sdAdjust button{min-height:42px}.sdMode button,.sdPresets button{min-height:40px}}';document.head.appendChild(s)}
  function bind(){injectStyle();try{cvdLine.applyOptions({visible:false})}catch{}const box=document.getElementById('cvdToggle');if(box){box.checked=true;box.onchange=e=>setVisible(e.target.checked);const span=box.closest('span');if(span){[...span.childNodes].forEach(n=>{if(n.nodeType===3)n.remove()});span.append(' SD Linear Regression Channel')}const label=box.closest('label');if(label){label.title='SD regression channel';addControls(label)}}refresh(true)}
  window.SDCLRD={refresh,setVisible,get settings(){return{...cfg,...active()}},setMode:m=>{cfg.mode=m==='manual'?'manual':'auto';save()}};setTimeout(bind,0);setInterval(()=>refresh(false),1800);['tf','qtf'].forEach(id=>document.getElementById(id)?.addEventListener('change',()=>setTimeout(()=>refresh(true),450)));
})();