(()=>{
  const $=id=>document.getElementById(id);
  const state={tf:'15m',chartType:'candles',candles:[],chart:null,candleSeries:null,lineSeries:null,volumeSeries:null,lastTick:null,lastTickAt:0,lastRate:null,busy:new Set(),health:{},lastPaint:0};
  const fmtPrice=v=>Number.isFinite(+v)&&+v>0?'$'+Number(v).toFixed(10).replace(/0+$/,'').replace(/\.$/,''):'—';
  const fmtMoney=v=>{v=+v||0;const a=Math.abs(v);return a>=1e9?'$'+(v/1e9).toFixed(2)+'B':a>=1e6?'$'+(v/1e6).toFixed(2)+'M':a>=1e3?'$'+(v/1e3).toFixed(1)+'K':'$'+v.toFixed(0)};
  const pct=v=>Number.isFinite(+v)?((+v>=0?'+':'')+(+v).toFixed(2)+'%'):'—';
  const age=ts=>{if(!ts)return'—';const s=Math.max(0,Math.round((Date.now()-ts)/1000));return s<60?s+'s ago':Math.round(s/60)+'m ago'};
  async function getJSON(url,key,timeout=7000){if(state.busy.has(key))return null;state.busy.add(key);const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error(String(r.status));const j=await r.json();state.health[key]={ok:true,ts:Date.now()};return j}catch(e){state.health[key]={ok:false,ts:Date.now(),error:String(e?.message||e)};return null}finally{clearTimeout(t);state.busy.delete(key);paintHealth()}}
  function setupChart(){const el=$('chart');if(!window.LightweightCharts||!el){$('chartFallback').hidden=false;return}state.chart=LightweightCharts.createChart(el,{width:el.clientWidth,height:el.clientHeight,layout:{background:{color:'#081019'},textColor:'#90a0ad'},grid:{vertLines:{color:'#14212b'},horzLines:{color:'#14212b'}},rightPriceScale:{borderColor:'#2b3b47'},timeScale:{borderColor:'#2b3b47',timeVisible:true,secondsVisible:false},crosshair:{mode:0}});state.candleSeries=state.chart.addCandlestickSeries({upColor:'#61e781',downColor:'#ff6d74',borderVisible:false,wickUpColor:'#61e781',wickDownColor:'#ff6d74',priceFormat:{type:'price',precision:10,minMove:.0000000001}});state.lineSeries=state.chart.addLineSeries({visible:false,lineWidth:2,priceFormat:{type:'price',precision:10,minMove:.0000000001}});state.volumeSeries=state.chart.addHistogramSeries({priceScaleId:'vol',lastValueVisible:false,priceLineVisible:false,priceFormat:{type:'volume'}});state.chart.priceScale('vol').applyOptions({scaleMargins:{top:.82,bottom:0},visible:false});let rt;addEventListener('resize',()=>{clearTimeout(rt);rt=setTimeout(()=>{try{state.chart.resize(el.clientWidth,el.clientHeight)}catch{}},160)})}
  function calcATR(c){if(c.length<15)return null;const a=[];for(let i=Math.max(1,c.length-20);i<c.length;i++){const x=c[i],p=c[i-1];a.push(Math.max(x.high-x.low,Math.abs(x.high-p.close),Math.abs(x.low-p.close)))}return a.length?a.reduce((s,v)=>s+v,0)/a.length:null}
  function paintChart(data,fit=false){if(!data.length)return;state.candles=data;const rows=data.map(x=>({time:+x.time,open:+x.open,high:+x.high,low:+x.low,close:+x.close}));const vols=data.map(x=>({time:+x.time,value:+x.volume||0,color:x.close>=x.open?'rgba(97,231,129,.45)':'rgba(255,109,116,.45)'}));try{state.candleSeries.setData(rows);state.lineSeries.setData(data.map(x=>({time:+x.time,value:+x.close})));state.volumeSeries.setData(vols);if(fit)state.chart.timeScale().fitContent()}catch{}const last=data[data.length-1];$('chartPrice').textContent=fmtPrice(last.close);$('chartMeta').textContent=state.tf.toUpperCase()+' · '+data.length+' candles';const atr=calcATR(data);if(atr&&$('atr'))$('atr').textContent=(atr/last.close*100).toFixed(2)+'%'}
  async function loadCandles(fit=false){const lim=state.tf==='1m'?900:state.tf==='5m'?576:state.tf==='15m'?480:state.tf==='30m'?360:320;const j=await getJSON('/api/mobile-candles?interval='+encodeURIComponent(state.tf)+'&limit='+lim+'&t='+Date.now(),'candles',8000);if(j?.ok&&Array.isArray(j.candles)){paintChart(j.candles,fit);$('chartState').textContent='● LIVE';$('chartState').className='live'}else{$('chartState').textContent='● RETRYING';$('chartState').className='warn'}}
  async function loadSummary(){const j=await getJSON('/api/market-summary?t='+Date.now(),'summary');if(!j?.ok)return;$('mainPrice').textContent=fmtPrice(j.price);$('change24').textContent=pct(j.change24);$('change24').className=+j.change24>=0?'up':'down';$('high24').textContent=fmtPrice(j.high24);$('low24').textContent=fmtPrice(j.low24);$('vol24').textContent=fmtMoney(j.quoteVolume);$('updated').textContent=new Date(j.ts).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}
  async function loadPrediction(){const s=await getJSON('/api/mobile-learning?t='+Date.now(),'prediction',8000);if(!s?.ok)return;const m=s.latest||{},dir=m.dir||'NEUTRAL',el=$('direction');el.textContent=dir==='BULLISH'?'LIKELY UP':dir==='BEARISH'?'LIKELY DOWN':'UNCLEAR / SIDEWAYS';el.className='direction '+(dir==='BULLISH'?'up':dir==='BEARISH'?'down':'neutral');$('confidence').textContent=Number.isFinite(+m.conf)?Math.round(+m.conf)+'%':'—';$('regime').textContent=m.regime||'—';$('modelPrice').textContent=fmtPrice(+m.price);$('probUp').textContent=Number.isFinite(+m.up)?Math.round(+m.up)+'%':'—';$('probFlat').textContent=Number.isFinite(+m.neutral)?Math.round(+m.neutral)+'%':'—';$('probDown').textContent=Number.isFinite(+m.down)?Math.round(+m.down)+'%':'—';const g=s.global||{};$('hitRate').textContent=g.completed?Math.round((+g.hitRate||0)*100)+'% · '+g.correct+'/'+g.completed:'CALIBRATING';$('learnRuns').textContent=(s.runCount||0)+' runs';$('learnAge').textContent=s.updatedAt?age(Date.parse(s.updatedAt)):'—';const atr=calcATR(state.candles),p=+m.price||state.candles.at(-1)?.close;if(atr&&p){const mult=m.regime==='BREAKOUT'?1.35:m.regime==='TRENDING'?1.1:m.regime==='LOW VOLATILITY'?0.75:0.9;$('range').textContent=fmtPrice(Math.max(0,p-atr*mult))+' – '+fmtPrice(p+atr*mult)}$('predStatus').textContent='● SERVER V9 LIVE';$('predStatus').className='live'}
  function renderTrades(a){const rows=(a||[]).slice().sort((x,y)=>(+y.t)-(+x.t)).slice(0,24);$('tradeRows').innerHTML=rows.map(t=>{const s=String(t.s).toLowerCase()==='sell'?'sell':'buy',usd=(+t.p)*(+t.q);return `<div class="trade ${s}"><span>${s==='buy'?'↑':'↓'} ${fmtPrice(+t.p)}</span><b>${t.ex||'—'}</b><span>${fmtMoney(usd)}</span><span>${new Date(+t.t||Date.now()).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</span></div>`}).join('')||'<div class="empty">Waiting for trades…</div>'}
  async function loadTrades(){const j=await getJSON('/api/live-trades?unified=1&t='+Date.now(),'trades',8500);if(!j?.ok)return;const all=(j.trades||[]).filter(t=>+t.p>0&&+t.q>0),recent=all.filter(t=>+t.t>Date.now()-120000);let buy=0,sell=0;recent.forEach(t=>{const v=(+t.p)*(+t.q);String(t.s).toLowerCase()==='sell'?sell+=v:buy+=v});const total=buy+sell,bp=total?buy/total:.5;$('buyShare').textContent=Math.round(bp*100)+'%';$('sellShare').textContent=Math.round((1-bp)*100)+'%';$('flowUsd').textContent=(buy-sell>=0?'+':'')+fmtMoney(buy-sell);$('flowUsd').className=buy-sell>=0?'up':'down';$('tradeCount').textContent=recent.length;$('feedCount').textContent=Object.values(j.status||{}).filter(Boolean).length+'/5';renderTrades(all)}
  async function loadBook(){const j=await getJSON('/api/orderbook?unified=1&t='+Date.now(),'book',9000);if(!j?.ok)return;const im=+j.imbalance||0;$('bookImbalance').textContent=(im>=0?'+':'')+(im*100).toFixed(1)+'%';$('bookImbalance').className=im>=0?'up':'down';$('bookConsensus').textContent=j.consensus||'MIXED';$('bookSources').textContent=(j.sources||0)+' exchanges';$('bookAgreement').textContent=Math.round((+j.agreement||0)*100)+'%';$('spread').textContent=Number.isFinite(+j.spreadBps)?(+j.spreadBps).toFixed(1)+' bps':'—';$('liveConfirm').textContent=im>.08?'ORDER BOOK SUPPORTS UP':im<-.08?'ORDER BOOK SUPPORTS DOWN':'ORDER BOOK MIXED';$('liveConfirm').className=im>.08?'up':im<-.08?'down':'neutral'}
  async function loadNetwork(){const j=await getJSON('/api/network-status?t='+Date.now(),'network',8000);if(!j?.ok){$('netState').textContent='● RETRYING';$('netState').className='warn';return}const now=Date.now(),tick=+j.tick;if(Number.isFinite(tick)){if(state.lastTick!=null&&tick>=state.lastTick&&state.lastTickAt){const dt=(now-state.lastTickAt)/1000;if(dt>.3)state.lastRate=(tick-state.lastTick)/dt}state.lastTick=tick;state.lastTickAt=now}$('netTick').textContent=Number.isFinite(tick)?tick.toLocaleString():'—';$('netEpoch').textContent=j.epoch??'—';$('netLatency').textContent=(j.latency||0)+' ms';$('netRate').textContent=state.lastRate==null?'CALCULATING':state.lastRate.toFixed(2)+' ticks/s';$('netState').textContent='● RPC LIVE';$('netState').className='live'}
  async function loadAnt(){const j=await getJSON('/api/ant-score?t='+Date.now(),'ant',8000);if(!j?.ok)return;const score=Number(j.score??j.antScore??j.value);$('antScore').textContent=Number.isFinite(score)?score.toFixed(1):'LIVE';$('antMeta').textContent=j.signal||j.bias||'LIVE ANALYSIS'}
  function paintHealth(){const map=[['candles','Chart data'],['prediction','Prediction'],['book','Order books'],['trades','Trade flow'],['network','Qubic network']];$('healthGrid').innerHTML=map.map(([k,n])=>{const h=state.health[k],ok=h?.ok&&Date.now()-h.ts<60000;return `<div><i class="${ok?'ok':'bad'}"></i><span>${n}</span><b>${h?age(h.ts):'waiting'}</b></div>`}).join('')}
  function setType(type){state.chartType=type;document.querySelectorAll('[data-type]').forEach(b=>b.classList.toggle('active',b.dataset.type===type));try{state.candleSeries.applyOptions({visible:type==='candles'});state.lineSeries.applyOptions({visible:type==='line'})}catch{}}
  function bind(){document.querySelectorAll('[data-tf]').forEach(b=>b.onclick=()=>{if(state.tf===b.dataset.tf)return;state.tf=b.dataset.tf;document.querySelectorAll('[data-tf]').forEach(x=>x.classList.toggle('active',x===b));loadCandles(true)});document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>setType(b.dataset.type));$('fitBtn').onclick=()=>{try{state.chart.timeScale().fitContent()}catch{}};$('liveBtn').onclick=()=>{try{state.chart.timeScale().scrollToRealTime()}catch{}};$('refreshBtn').onclick=refreshAll}
  function refreshAll(){if(document.hidden)return;loadSummary();loadCandles(false);loadPrediction();loadTrades();loadBook();loadNetwork();loadAnt()}
  function boot(){setupChart();bind();paintHealth();loadCandles(true);loadSummary();loadPrediction();loadTrades();loadBook();loadNetwork();loadAnt();setInterval(()=>{if(!document.hidden){loadSummary();loadCandles(false)}},15000);setInterval(()=>{if(!document.hidden){loadTrades();loadBook()}},12000);setInterval(()=>{if(!document.hidden){loadNetwork();loadAnt()}},10000);setInterval(()=>{if(!document.hidden)loadPrediction()},30000);setInterval(paintHealth,10000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(refreshAll,400)})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
