const VERCEL_FALLBACK='https://qubic-intelligence-competition.vercel.app';
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, max-age=0','access-control-allow-origin':'*','access-control-allow-methods':'GET,HEAD,OPTIONS',...extra}});
const timeout=(p,ms=4500)=>Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(new Error('timeout')),ms))]);
async function getJson(url,ms=4500){const r=await timeout(fetch(url,{cache:'no-store',headers:{accept:'application/json','user-agent':'QubicLiveChart-Cloudflare/2.0'}}),ms);if(!r.ok)throw Error(String(r.status));return r.json()}
const normTs=t=>{const n=+t||0;return n<1e12?n*1000:n};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const median=a=>{a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const m=a.length>>1;return a.length%2?a[m]:(a[m-1]+a[m])/2};

let activityCache={ts:0,chosen:null,scores:{}};
function scoreRows(rows,now){let usd=0,n=0,last=0;for(const x of rows){const t=normTs(x.t),p=+x.p,q=+x.q;if(t>=now-120000&&p>0&&q>0){usd+=p*q;n++;last=Math.max(last,t)}}return{usd,n,last,score:usd*(1+Math.min(n,80)/80)*(last>now-20000?1.15:1)}}
async function exchangeActivity(){const now=Date.now();if(now-activityCache.ts<15000&&activityCache.chosen)return activityCache;const rows={GATE:[],MEXC:[],BITGET:[],COINEX:[],LBANK:[]};const push=(ex,p,q,t)=>rows[ex].push({p:+p,q:+q,t:normTs(t)});await Promise.allSettled([
getJson('https://api.gateio.ws/api/v4/spot/trades?currency_pair=QUBIC_USDT&limit=100').then(a=>a.forEach(x=>push('GATE',x.price,x.amount,x.create_time_ms||x.create_time))),
getJson('https://api.mexc.com/api/v3/trades?symbol=QUBICUSDT&limit=100').then(a=>a.forEach(x=>push('MEXC',x.price,x.qty,x.time))),
getJson('https://api.bitget.com/api/v2/spot/market/fills?symbol=QUBICUSDT&limit=100').then(x=>(x.data||[]).forEach(v=>push('BITGET',v.price||v.px,v.size||v.sz,v.ts||v.time))),
getJson('https://api.coinex.com/v2/spot/deals?market=QUBICUSDT&limit=100').then(x=>(x.data||[]).forEach(v=>push('COINEX',v.price,v.amount,v.created_at||v.createdAt||v.time))),
getJson('https://api.lbkex.com/v2/trades.do?symbol=qubic_usdt&size=100').then(x=>(x.data||[]).forEach(v=>push('LBANK',v.price,v.amount||v.volume,v.date_ms||v.date||v.time)))
]);const scores={};for(const[k,v]of Object.entries(rows))scores[k]=scoreRows(v,now);const ranked=Object.entries(scores).sort((a,b)=>b[1].score-a[1].score);activityCache={ts:now,chosen:ranked[0]?.[0]||'GATE',scores};return activityCache}
const maps={GATE:{'1m':'1m','5m':'5m','15m':'15m','30m':'30m','1h':'1h','4h':'4h','1d':'1d'},MEXC:{'1m':'1m','5m':'5m','15m':'15m','30m':'30m','1h':'60m','4h':'4h','1d':'1d'},BITGET:{'1m':'1min','5m':'5min','15m':'15min','30m':'30min','1h':'1h','4h':'4h','1d':'1day'},COINEX:{'1m':'1min','5m':'5min','15m':'15min','30m':'30min','1h':'1hour','4h':'4hour','1d':'1day'},LBANK:{'1m':'minute1','5m':'minute5','15m':'minute15','30m':'minute30','1h':'hour1','4h':'hour4','1d':'day1'}};
const sec={'1m':60,'5m':300,'15m':900,'30m':1800,'1h':3600,'4h':14400,'1d':86400};
async function exchangeCandles(ex,iv,limit){if(ex==='GATE'){const a=await getJson(`https://api.gateio.ws/api/v4/spot/candlesticks?currency_pair=QUBIC_USDT&interval=${maps.GATE[iv]}&limit=${limit}`);return a.map(x=>({time:+x[0],open:+x[5],high:+x[3],low:+x[4],close:+x[2],volume:+x[1]||0}))}if(ex==='MEXC'){const a=await getJson(`https://api.mexc.com/api/v3/klines?symbol=QUBICUSDT&interval=${maps.MEXC[iv]}&limit=${limit}`);return a.map(x=>({time:Math.floor(+x[0]/1000),open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[5]||0}))}if(ex==='BITGET'){const x=await getJson(`https://api.bitget.com/api/v2/spot/market/candles?symbol=QUBICUSDT&granularity=${maps.BITGET[iv]}&limit=${Math.min(limit,1000)}`);return(x.data||[]).map(v=>({time:Math.floor(+v[0]/1000),open:+v[1],high:+v[2],low:+v[3],close:+v[4],volume:+v[5]||0}))}if(ex==='COINEX'){const x=await getJson(`https://api.coinex.com/v2/spot/kline?market=QUBICUSDT&period=${maps.COINEX[iv]}&limit=${Math.min(limit,1000)}`);return(x.data||[]).map(v=>({time:Math.floor(+(v.created_at||v.createdAt)/1000),open:+v.open,high:+v.high,low:+v.low,close:+v.close,volume:+v.volume||0}))}if(ex==='LBANK'){const start=Math.floor(Date.now()/1000)-Math.min(limit,2000)*sec[iv];const x=await getJson(`https://api.lbank.info/v2/kline.do?symbol=qubic_usdt&size=${Math.min(limit,2000)}&type=${maps.LBANK[iv]}&time=${start}`);return(x.data||[]).map(v=>({time:+v[0],open:+v[1],high:+v[2],low:+v[3],close:+v[4],volume:+v[5]||0}))}return[]}
async function activeCandles(url){const allowed=['1m','5m','15m','30m','1h','4h','1d'];const iv=allowed.includes(url.searchParams.get('interval'))?url.searchParams.get('interval'):'15m';const limit=Math.max(60,Math.min(1000,+(url.searchParams.get('limit')||480)));const prefer=String(url.searchParams.get('prefer')||'').toUpperCase();const a=await exchangeActivity();const ranked=Object.entries(a.scores).sort((x,y)=>y[1].score-x[1].score);let chosen=a.chosen;const top=ranked[0]?.[1]?.score||0;if(prefer&&a.scores[prefer]&&a.scores[prefer].score>=top*.65)chosen=prefer;const order=[chosen,...ranked.map(x=>x[0]),'GATE'].filter((v,i,s)=>v&&s.indexOf(v)===i);let data=[],source=null;const minHistory=Math.min(80,Math.max(40,Math.floor(limit*.15))),rejected={};for(const ex of order){try{const d=(await exchangeCandles(ex,iv,limit)).filter(x=>Number.isFinite(x.time)&&x.open>0&&x.high>0&&x.low>0&&x.close>0).sort((x,y)=>x.time-y.time);if(d.length>=minHistory){data=d;source=ex;break}rejected[ex]=d.length}catch(e){rejected[ex]=String(e?.message||e)}}if(!data.length)return{status:503,body:{ok:false,error:'No active exchange has enough candle history',interval:iv,minHistory,rejected,ts:Date.now()}};return{status:200,body:{ok:true,platform:'cloudflare-native',interval:iv,source,activity:a.scores,minHistory,rejected,candles:data,ts:Date.now()}}}

function avwap(rows,start){let pv=0,v=0,out=[];for(let i=start;i<rows.length;i++){const c=rows[i],tp=(c.high+c.low+c.close)/3,vol=Math.max(0,+c.volume||0);pv+=tp*vol;v+=vol;out.push({time:c.time,value:v?pv/v:tp})}return out}
function slope(a){if(a.length<4)return 0;const x=a.slice(-4);return(x.at(-1).value-x[0].value)/Math.max(Math.abs(x[0].value),1e-15)}
function swing(rows,type,look=80){let best=null;for(let i=Math.max(2,rows.length-look);i<rows.length-2;i++){const c=rows[i];if(type==='low'&&c.low<=rows[i-1].low&&c.low<=rows[i+1].low){if(!best||c.low<best.v)best={i,v:c.low,time:c.time}}if(type==='high'&&c.high>=rows[i-1].high&&c.high>=rows[i+1].high){if(!best||c.high>best.v)best={i,v:c.high,time:c.time}}}return best}
function analyzeAvwap(rows,tf,source){rows=(rows||[]).filter(x=>+x.close>0&&+x.high>0&&+x.low>0&&+x.open>0).sort((a,b)=>a.time-b.time);if(rows.length<60)return null;const last=rows.at(-1),vols=rows.slice(-40).map(x=>+x.volume||0),v20=avg(vols.slice(-20));let hv=null;for(let i=Math.max(1,rows.length-80);i<rows.length;i++){const ratio=v20?((+rows[i].volume||0)/v20):0;if(ratio>=1.5&&(!hv||ratio>hv.ratio))hv={i,ratio,time:rows[i].time}}const lo=swing(rows,'low'),hi=swing(rows,'high'),anchors=[];if(hv)anchors.push({type:'HIGH VOLUME',i:hv.i});if(lo)anchors.push({type:'SWING LOW',i:lo.i});if(hi)anchors.push({type:'SWING HIGH',i:hi.i});if(!anchors.length)anchors.push({type:'RECENT',i:Math.max(0,rows.length-40)});const lines=anchors.map(a=>{const z=avwap(rows,a.i),now=z.at(-1)?.value||last.close;return{type:a.type,time:rows[a.i].time,value:now,slope:slope(z),distancePct:(last.close/now-1)*100}});let bull=0,bear=0;for(const l of lines){if(last.close>l.value&&l.slope>=0)bull++;else if(last.close<l.value&&l.slope<=0)bear++}const direction=bull>bear?'UP':bear>bull?'DOWN':'NEUTRAL',score=Math.round(clamp(50+Math.abs(bull-bear)*12+Math.min(18,Math.max(...lines.map(x=>Math.abs(x.distancePct)))),50,92));let pinch=null;if(lo&&hi){const a=avwap(rows,lo.i),b=avwap(rows,hi.i),va=a.at(-1)?.value,vb=b.at(-1)?.value;if(va&&vb){const spread=Math.abs(va-vb)/last.close*100;pinch={active:spread<1.1,spreadPct:+spread.toFixed(3),upper:Math.max(va,vb),lower:Math.min(va,vb)}}}return{tf,source,price:last.close,direction,score,bull,bear,anchors:lines,pinch,highVolumeRatio:hv?+hv.ratio.toFixed(2):null}}
async function avwapSignal(){const tfs=['5m','15m','1h','4h'];const settled=await Promise.allSettled(tfs.map(async tf=>{const u=new URL('https://internal.invalid/api/active-candles');u.searchParams.set('interval',tf);u.searchParams.set('limit','320');const r=await activeCandles(u);if(r.status!==200)throw Error(tf);return analyzeAvwap(r.body.candles,tf,r.body.source||'—')}));const frames=settled.filter(x=>x.status==='fulfilled'&&x.value).map(x=>x.value);if(!frames.length)return{status:503,body:{ok:false,error:'No AVWAP frames',ts:Date.now()}};const up=frames.filter(x=>x.direction==='UP').length,down=frames.filter(x=>x.direction==='DOWN').length,neutral=frames.length-up-down,direction=up>down?'UP':down>up?'DOWN':'NEUTRAL',alignment=Math.round(Math.max(up,down,neutral)/frames.length*100),strength=Math.round(avg(frames.filter(x=>x.direction===direction).map(x=>x.score))||50),pinchFrames=frames.filter(x=>x.pinch?.active).map(x=>x.tf),state=direction==='UP'?1:direction==='DOWN'?-1:0;return{status:200,body:{ok:true,platform:'cloudflare-native',engine:'AVWAP CONFLUENCE',state,direction,alignment,strength,pinchFrames,frames,ts:Date.now()}}}

const BOOKS=[{name:'GATE',url:'https://api.gateio.ws/api/v4/spot/order_book?currency_pair=QUBIC_USDT&limit=50',parse:x=>({bids:x.bids,asks:x.asks,ts:x.current||Date.now()})},{name:'MEXC',url:'https://api.mexc.com/api/v3/depth?symbol=QUBICUSDT&limit=50',parse:x=>({bids:x.bids,asks:x.asks,ts:Date.now()})},{name:'BITGET',url:'https://api.bitget.com/api/v3/market/orderbook?category=SPOT&symbol=QUBICUSDT&limit=50',parse:x=>({bids:x.data?.b||x.data?.bids,asks:x.data?.a||x.data?.asks,ts:+(x.data?.ts||x.requestTime)||Date.now()})},{name:'COINEX',url:'https://api.coinex.com/v2/spot/depth?market=QUBICUSDT&limit=50&interval=0',parse:x=>({bids:x.data?.depth?.bids,asks:x.data?.depth?.asks,ts:+x.data?.depth?.updated_at||Date.now()})},{name:'LBANK',url:'https://api.lbank.info/v2/depth.do?symbol=qubic_usdt&size=50',parse:x=>({bids:x.data?.bids,asks:x.data?.asks,ts:+(x.data?.timestamp||x.ts)||Date.now()})}];
function analyseBook(name,book){let bids=(book.bids||[]).map(x=>[+x[0],+x[1]]).filter(x=>x[0]>0&&x[1]>0).sort((a,b)=>b[0]-a[0]),asks=(book.asks||[]).map(x=>[+x[0],+x[1]]).filter(x=>x[0]>0&&x[1]>0).sort((a,b)=>a[0]-b[0]);if(!bids.length||!asks.length)throw Error('empty book');const bid=bids[0][0],ask=asks[0][0],mid=(bid+ask)/2,spreadBps=(ask-bid)/mid*10000;if(!Number.isFinite(mid)||spreadBps<0||spreadBps>500)throw Error('invalid spread');const depth=(levels,side,pct)=>levels.filter(([p])=>side==='bid'?p>=mid*(1-pct):p<=mid*(1+pct)).reduce((s,[p,q])=>s+p*q,0),bid05=depth(bids,'bid',.005),ask05=depth(asks,'ask',.005),bid1=depth(bids,'bid',.01),ask1=depth(asks,'ask',.01),imb05=(bid05-ask05)/Math.max(1,bid05+ask05),imb1=(bid1-ask1)/Math.max(1,bid1+ask1),topBid=bids.slice(0,10).reduce((s,[p,q])=>s+p*q,0),topAsk=asks.slice(0,10).reduce((s,[p,q])=>s+p*q,0),topImb=(topBid-topAsk)/Math.max(1,topBid+topAsk);return{name,mid,spreadBps,bid05,ask05,bid1,ask1,imbalance:.5*imb05+.3*imb1+.2*topImb,ts:book.ts||Date.now()}}
async function orderbook(){const settled=await Promise.allSettled(BOOKS.map(async s=>analyseBook(s.name,s.parse(await getJson(s.url,3500))))),books=settled.filter(x=>x.status==='fulfilled').map(x=>x.value),failed=settled.map((x,i)=>x.status==='rejected'?BOOKS[i].name:null).filter(Boolean);if(!books.length)return{status:503,body:{ok:false,error:'No order books available',failed,ts:Date.now()}};const imbs=books.map(x=>x.imbalance),imbalance=median(imbs),buyVotes=imbs.filter(x=>x>.08).length,sellVotes=imbs.filter(x=>x<-.08).length,neutralVotes=books.length-buyVotes-sellVotes,consensus=buyVotes>sellVotes?'BUY':sellVotes>buyVotes?'SELL':'MIXED',agreement=Math.max(buyVotes,sellVotes,neutralVotes)/books.length;return{status:200,body:{ok:true,platform:'cloudflare-native',mid:median(books.map(x=>x.mid)),imbalance,consensus,agreement,buyVotes,sellVotes,neutralVotes,sources:books.length,spreadBps:median(books.map(x=>x.spreadBps)),books,failed,ts:Date.now()}}}

async function liveTrades(){const out=[],status={},now=Date.now(),push=(ex,p,q,s,t,id)=>{p=+p;q=+q;t=normTs(t||now);if(p>0&&q>0&&t>now-600000&&t<now+60000)out.push({ex,p,q,s:String(s).toLowerCase().includes('sell')?'sell':'buy',t,id:String(id||'')})};const jobs=[['GATE',async()=>{(await getJson('https://api.gateio.ws/api/v4/spot/trades?currency_pair=QUBIC_USDT&limit=100',3500)).forEach(x=>push('GATE',x.price,x.amount,x.side,x.create_time_ms||x.create_time,x.id))}],['MEXC',async()=>{(await getJson('https://api.mexc.com/api/v3/trades?symbol=QUBICUSDT&limit=100',3500)).forEach(x=>push('MEXC',x.price,x.qty,x.isBuyerMaker?'sell':'buy',x.time,x.id))}],['BITGET',async()=>{const x=await getJson('https://api.bitget.com/api/v2/spot/market/fills?symbol=QUBICUSDT&limit=100',3500);(x.data||[]).forEach(v=>push('BITGET',v.price||v.px,v.size||v.sz,v.side,v.ts||v.time,v.tradeId||v.id))}],['COINEX',async()=>{const x=await getJson('https://api.coinex.com/v2/spot/deals?market=QUBICUSDT&limit=100',3500);(x.data||[]).forEach(v=>push('COINEX',v.price,v.amount,v.side,v.created_at||v.createdAt||v.time,v.deal_id||v.id))}],['LBANK',async()=>{const x=await getJson('https://api.lbkex.com/v2/trades.do?symbol=qubic_usdt&size=100',3500);(x.data||[]).forEach(v=>push('LBANK',v.price,v.amount||v.volume,v.type==='sell'||v.direction==='sell'?'sell':'buy',v.date_ms||v.date||v.time,v.tid||v.id))}]];await Promise.all(jobs.map(async([n,fn])=>{try{await fn();status[n]=true}catch{status[n]=false}}));out.sort((a,b)=>a.t-b.t);return{status:200,body:{ok:true,platform:'cloudflare-native',ts:now,status,trades:out.slice(-350)}}}

const sd=a=>{if(a.length<2)return 0;const m=avg(a);return Math.sqrt(avg(a.map(x=>(x-m)**2)))};
const atr=a=>{if(a.length<3)return 0;const r=[];for(let i=1;i<a.length;i++){const c=a[i],p=a[i-1];r.push(Math.max(c.high-c.low,Math.abs(c.high-p.close),Math.abs(c.low-p.close)))}return avg(r)};
function detectPattern(rows,tf,source){const a=(rows||[]).slice().sort((x,y)=>+x.time-+y.time).filter(x=>+x.open>0&&+x.high>0&&+x.low>0&&+x.close>0);if(a.length<45)return{tf,source,status:'INSUFFICIENT',score:0,direction:'NEUTRAL'};const last=a.at(-1),recent=a.slice(-24),base=a.slice(-48,-12),rAtr=atr(recent),bAtr=atr(base)||rAtr||1e-12,compression=clamp(1-rAtr/bAtr,0,1),hi=Math.max(...a.slice(-21,-1).map(x=>x.high)),lo=Math.min(...a.slice(-21,-1).map(x=>x.low)),span=Math.max(hi-lo,last.close*.000001),closes=recent.map(x=>x.close),rets=closes.slice(1).map((x,i)=>x/closes[i]-1),vol=Math.max(sd(rets),1e-9),momentum=clamp(avg(rets.slice(-5))/vol,-3,3),bodies=recent.slice(-6).map(x=>Math.abs(x.close-x.open)/Math.max(x.high-x.low,1e-12)),bodyStrength=avg(bodies),vols=recent.map(x=>+x.volume||0),vNow=avg(vols.slice(-3)),vBase=avg(vols.slice(-18,-3))||vNow||1,volExpand=clamp(vNow/vBase-1,0,2)/2;let higher=0,lower=0;for(let i=recent.length-7;i<recent.length;i++){if(i<=0)continue;if(recent[i].low>recent[i-1].low)higher++;if(recent[i].high<recent[i-1].high)lower++}const structure=(higher-lower)/6,upProx=clamp(1-(hi-last.close)/Math.max(rAtr*2,1e-12),0,1),dnProx=clamp(1-(last.close-lo)/Math.max(rAtr*2,1e-12),0,1),bullRaw=.27*compression+.22*upProx+.18*clamp((momentum+1)/2,0,1)+.14*clamp((structure+1)/2,0,1)+.11*volExpand+.08*bodyStrength,bearRaw=.27*compression+.22*dnProx+.18*clamp((-momentum+1)/2,0,1)+.14*clamp((-structure+1)/2,0,1)+.11*volExpand+.08*bodyStrength;let direction=bullRaw-bearRaw>.08?'UP':bearRaw-bullRaw>.08?'DOWN':'NEUTRAL',score=Math.round(clamp(Math.max(bullRaw,bearRaw)*100,0,99)),status='NO SETUP';const brokeUp=last.close>hi&&last.close>last.open,brokeDown=last.close<lo&&last.close<last.open,impulse=Math.abs(last.close-last.open)>rAtr*.65&&bodyStrength>.55;if((brokeUp||brokeDown)&&impulse)status='BREAKOUT STARTING';else if(score>=72&&compression>.18)status='BUILDING PRESSURE';else if(score>=62&&(upProx>.7||dnProx>.7))status='EARLY SETUP';else if(score>=56)status='WATCHING';const run=recent.slice(-8),move=(run.at(-1).close/run[0].open)-1;if(Math.abs(move)>rAtr/last.close*2.6&&((direction==='UP'&&last.close<run.at(-2).close)||(direction==='DOWN'&&last.close>run.at(-2).close)))status='REVERSAL RISK';return{tf,source,status,score,direction,compression:Math.round(compression*100),breakoutProximity:Math.round(Math.max(upProx,dnProx)*100),volumeExpansion:Math.round(volExpand*100),structure:Math.round(structure*100),momentum:+momentum.toFixed(2),price:last.close}}
async function patternScan(){const tfs=['1m','5m','15m','30m','1h','4h','1d'],out=await Promise.all(tfs.map(async tf=>{try{const u=new URL('https://internal.invalid/api/active-candles');u.searchParams.set('interval',tf);u.searchParams.set('limit','220');const r=await activeCandles(u);if(r.status!==200)throw Error('candles');return detectPattern(r.body.candles,tf,r.body.source||'—')}catch{return{tf,source:'—',status:'UNAVAILABLE',score:0,direction:'NEUTRAL'}}})),valid=out.filter(x=>x.score>0),bull=valid.filter(x=>x.direction==='UP').reduce((s,x)=>s+x.score,0),bear=valid.filter(x=>x.direction==='DOWN').reduce((s,x)=>s+x.score,0),aligned=Math.max(bull,bear)/(valid.reduce((s,x)=>s+x.score,0)||1),direction=bull>bear*1.12?'UP':bear>bull*1.12?'DOWN':'NEUTRAL',strongest=valid.slice().sort((a,b)=>b.score-a.score)[0]||null;return{status:200,body:{ok:true,platform:'cloudflare-native',direction,alignment:Math.round(aligned*100),strongest,timeframes:out,ts:Date.now()}}}

async function proxyLegacyApi(request,url){const upstream=new URL(url.pathname+url.search,VERCEL_FALLBACK),headers=new Headers(request.headers);headers.delete('host');const init={method:request.method,headers,redirect:'follow'};if(!['GET','HEAD'].includes(request.method))init.body=request.body;const response=await fetch(upstream,init),out=new Headers(response.headers);out.set('x-qubic-cloudflare-stage','legacy-api-bridge');out.set('cache-control','no-store, max-age=0');out.set('access-control-allow-origin','*');return new Response(response.body,{status:response.status,headers:out})}
export default{async fetch(request,env){const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,HEAD,OPTIONS','access-control-allow-headers':'*'}});try{if(url.pathname==='/api/health')return json({ok:true,platform:'cloudflare-workers',project:'Qubic Live Chart',stage:'native-core-v2',native:['active-candles','avwap-signal','orderbook','live-trades','pattern-scan'],ts:Date.now()});if(url.pathname==='/api/active-candles'){const r=await activeCandles(url);return json(r.body,r.status)}if(url.pathname==='/api/avwap-signal'){const r=await avwapSignal();return json(r.body,r.status)}if(url.pathname==='/api/orderbook'){const r=await orderbook();return json(r.body,r.status)}if(url.pathname==='/api/live-trades'){const r=await liveTrades();return json(r.body,r.status)}if(url.pathname==='/api/pattern-scan'){const r=await patternScan();return json(r.body,r.status)}if(url.pathname.startsWith('/api/'))return await proxyLegacyApi(request,url);return env.ASSETS.fetch(request)}catch(e){return json({ok:false,error:String(e?.message||e),ts:Date.now()},502)}}};
