const OWNER='smzjcmv9bk-commits',REPO='Qubic-live-chart',BRANCH='learning-data',STATE_PATH='learning/v9-state.json';
const token=process.env.GITHUB_TOKEN;if(!token)throw new Error('GITHUB_TOKEN missing');
const H={Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const ema=(a,n)=>{if(!a.length)return 0;let k=2/(n+1),v=a[0];for(let i=1;i<a.length;i++)v=a[i]*k+v*(1-k);return v};
const sd=a=>{if(a.length<2)return 0;let m=a.reduce((s,x)=>s+x,0)/a.length;return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))};
const tern=(v,t=.18)=>v>t?1:v<-t?-1:0;
async function candles(interval,limit){let r=await fetch(`https://api.gateio.ws/api/v4/spot/candlesticks?currency_pair=QUBIC_USDT&interval=${interval}&limit=${limit}`,{headers:{'user-agent':'qubic-v9-learning'}});if(!r.ok)throw new Error(`candles ${interval} ${r.status}`);let a=await r.json();return a.map(x=>({time:+x[0],close:+x[2],high:+x[3],low:+x[4],open:+x[5],volume:+x[1]||0})).filter(x=>x.time&&x.close>0).sort((a,b)=>a.time-b.time)}
function sig(d){let c=d.map(x=>x.close);if(c.length<60)return null;let ret=[];for(let i=1;i<c.length;i++)ret.push(c[i]/c[i-1]-1);let vol=Math.max(sd(ret.slice(-64)),1e-7),p=c.at(-1),e9=ema(c.slice(-120),9),e21=ema(c.slice(-140),21),e50=ema(c.slice(-180),50),e100=ema(c.slice(-240),100),mFast=p/c.at(-5)-1,mSlow=p/c.at(-13)-1,trend=clamp(((e9/e21-1)+(e21/e50-1)*.8+(e50/e100-1)*.35)/vol,-3,3),momentum=clamp((mFast*.6+mSlow*.4)/vol,-3,3);return{p,trend,momentum,vol}}
async function book(){try{let r=await fetch('https://qubic-intelligence-competition.vercel.app/api/orderbook?worker=1',{headers:{'user-agent':'qubic-v9-learning'}}),x=await r.json();if(!r.ok||!x.ok)return{raw:0,ready:false};let vals=(x.books||[]).map(b=>clamp(+b.imbalance||0,-1,1));return{raw:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0,ready:vals.length>0}}catch{return{raw:0,ready:false}}}
async function flow(){try{let r=await fetch('https://qubic-intelligence-competition.vercel.app/api/live-trades?worker=1',{headers:{'user-agent':'qubic-v9-learning'}}),x=await r.json();let a=x.trades||x.data||[];let b=0,s=0;for(const t of a){let usd=+(t.usd||t.value||t.amountUsd||0);if(!usd&&+t.p>0&&+t.q>0)usd=(+t.p)*(+t.q);let side=String(t.side||t.s||'').toLowerCase();if(side==='buy')b+=usd;else if(side==='sell')s+=usd}let total=b+s;return{raw:total?(b-s)/total:0,ready:total>0}}catch{return{raw:0,ready:false}}}
async function readState(){let u=`https://api.github.com/repos/${OWNER}/${REPO}/contents/${STATE_PATH}?ref=${BRANCH}`,r=await fetch(u,{headers:H});if(r.status===404)return{state:{version:1,history:[],clusters:{},stateMem:[],global:{}},sha:null};if(!r.ok)throw new Error(`state read ${r.status}`);let x=await r.json();return{state:JSON.parse(Buffer.from(x.content,'base64').toString('utf8')),sha:x.sha}}
async function writeState(state,sha){let u=`https://api.github.com/repos/${OWNER}/${REPO}/contents/${STATE_PATH}`,body={message:'Update V9 24/7 learning state',content:Buffer.from(JSON.stringify(state)).toString('base64'),branch:BRANCH};if(sha)body.sha=sha;let r=await fetch(u,{method:'PUT',headers:{...H,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`state write ${r.status} ${await r.text()}`)}
function regime(s15,s1,s4){let strength=Math.abs(s1.trend)*.6+Math.abs(s4.trend)*.25+Math.abs(s15.trend)*.15;if(strength>1.35)return'TRENDING';if(Math.abs(s15.momentum)>1.6&&Math.sign(s15.momentum)===Math.sign(s1.trend))return'BREAKOUT';if(s1.vol<.006)return'LOW VOLATILITY';if(Math.abs(s1.trend)<.6)return'RANGING';return'TRANSITION'}
function makeModel(s15,s1,s4,b,f){let rg=regime(s15,s1,s4),trend=.32*s15.trend+.43*s1.trend+.25*s4.trend,mom=.45*s15.momentum+.4*s1.momentum+.15*s4.momentum,bookTerm=b.ready?clamp(b.raw*3,-2,2):0,flowTerm=f.ready?clamp(f.raw*2,-2,2):0;let weights=rg==='TRENDING'?{t:.42,m:.25,b:.12,f:.13}:rg==='BREAKOUT'?{t:.28,m:.3,b:.18,f:.2}:rg==='RANGING'?{t:.18,m:.2,b:.3,f:.24}:{t:.3,m:.27,b:.2,f:.17};let score=trend*weights.t+mom*weights.m+bookTerm*weights.b+flowTerm*weights.f,prob=1/(1+Math.exp(-1.9*score)),neutral=clamp(34-Math.abs(prob-.5)*46,10,34),up=prob*(100-neutral),down=(1-prob)*(100-neutral),edge=up-down,dir=Math.abs(edge)<15?'NEUTRAL':edge>0?'BULLISH':'BEARISH',conf=Math.round(clamp(Math.max(up,down,neutral),34,89));let cur={trend:tern(trend),momentum:tern(mom),flow:tern(flowTerm,.14),book:tern(bookTerm,.2)};let cluster=[rg,cur.trend,cur.momentum,cur.flow,cur.book].join('|');return{price:s15.p,dir,conf,cluster,regime:rg,states:cur,up:Math.round(up),down:Math.round(down),neutral:Math.round(neutral)}}
function evaluate(state,currentPrice,now){for(const p of state.history||[]){if(p.done||now-p.createdAt<3600000)continue;let move=currentPrice/p.price-1;p.done=true;p.move=move;p.resolvedAt=now;p.correct=p.dir==='BULLISH'?move>.001:p.dir==='BEARISH'?move<-.001:Math.abs(move)<=.001;if(p.dir!=='NEUTRAL'){let c=state.clusters[p.cluster]||(state.clusters[p.cluster]={n:0,ok:0,avg:0});c.n++;if(p.correct)c.ok++;c.avg+=(move-c.avg)/c.n}}}
const {state,sha}=await readState();state.version=2;state.history=Array.isArray(state.history)?state.history:[];state.clusters=state.clusters||{};state.stateMem=Array.isArray(state.stateMem)?state.stateMem:[];
const [d15,d1,d4,b,f]=await Promise.all([candles('15m',260),candles('1h',240),candles('4h',180),book(),flow()]);let s15=sig(d15),s1=sig(d1),s4=sig(d4);if(!s15||!s1||!s4)throw new Error('insufficient candle history');let m=makeModel(s15,s1,s4,b,f),now=Date.now();evaluate(state,m.price,now);
let last=state.history.at(-1);if(!last||now-last.createdAt>=14*60*1000)state.history.push({createdAt:now,bucket:Math.floor(now/900000)*900,price:m.price,dir:m.dir,confidence:m.conf,conf:m.conf,cluster:m.cluster,regime:m.regime,states:m.states,done:false});state.history=state.history.slice(-1000);state.stateMem.push({t:now,regime:m.regime,...m.states});state.stateMem=state.stateMem.slice(-500);
let completed=state.history.filter(x=>x.done&&x.dir!=='NEUTRAL'),correct=completed.filter(x=>x.correct).length;state.global={completed:completed.length,correct,hitRate:completed.length?correct/completed.length:null};state.latest={...m,bookReady:b.ready,flowReady:f.ready};state.updatedAt=new Date(now).toISOString();state.runCount=(state.runCount||0)+1;await writeState(state,sha);console.log(`V9 learner updated ${state.updatedAt} dir=${m.dir} conf=${m.conf}% completed=${completed.length}`);