const OWNER='smzjcmv9bk-commits',REPO='Qubic-live-chart',BRANCH='learning-data',STATE_PATH='learning/v9-state.json';
const PROD='https://qubic-intelligence-competition.vercel.app';
const token=process.env.GITHUB_TOKEN;if(!token)throw new Error('GITHUB_TOKEN missing');
const H={Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const sd=a=>{if(a.length<2)return 0;const m=a.reduce((s,x)=>s+x,0)/a.length;return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))};
const tern=(v,t=.15)=>v>t?1:v<-t?-1:0;
const dirNum=v=>{v=String(v||'').toUpperCase();return ['UP','BULLISH','BUY'].includes(v)?1:['DOWN','BEARISH','SELL'].includes(v)?-1:0};
async function json(path){const r=await fetch(path.startsWith('http')?path:`${PROD}${path}`,{cache:'no-store',headers:{'user-agent':'QubicUnifiedLearner/3.0'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`${path} ${r.status}`);return r.json()}
async function candles(interval,limit){const x=await json(`/api/active-candles?interval=${encodeURIComponent(interval)}&limit=${limit}&worker=1&t=${Date.now()}`);if(!x?.ok||!Array.isArray(x.candles))throw new Error(`candles ${interval} unavailable`);return x.candles.map(c=>({time:+c.time,open:+c.open,high:+c.high,low:+c.low,close:+c.close,volume:+c.volume||0})).filter(c=>c.time&&c.close>0).sort((a,b)=>a.time-b.time)}
function slopeNorm(vals,n=48){const a=vals.slice(-n);if(a.length<12)return 0;const logs=a.map(v=>Math.log(v)),N=logs.length,sx=N*(N-1)/2,sxx=(N-1)*N*(2*N-1)/6,sy=logs.reduce((s,v)=>s+v,0),sxy=logs.reduce((s,v,i)=>s+i*v,0),den=N*sxx-sx*sx;if(!den)return 0;const slope=(N*sxy-sx*sy)/den;const ret=[];for(let i=1;i<a.length;i++)ret.push(Math.log(a[i]/a[i-1]));return clamp(slope/Math.max(sd(ret),1e-7)*Math.sqrt(N),-3,3)}
function sig(d){const c=d.map(x=>x.close);if(c.length<60)return null;const ret=[];for(let i=1;i<c.length;i++)ret.push(c[i]/c[i-1]-1);const vol=Math.max(sd(ret.slice(-64)),1e-7),p=c.at(-1),mFast=p/c.at(-5)-1,mSlow=p/c.at(-13)-1,momentum=clamp((mFast*.62+mSlow*.38)/vol,-3,3),trend=slopeNorm(c,48),look=c.slice(-36),hi=Math.max(...look),lo=Math.min(...look),pos=(p-lo)/Math.max(1e-18,hi-lo),net=Math.abs(p-c.at(-25)),path=c.slice(-24).reduce((s,v,i,a)=>i?s+Math.abs(v-a[i-1]):s,0),eff=path?net/path:0,breakout=clamp((pos-.5)*2,-1,1);return{p,trend,momentum,vol,eff,breakout,pos}}
async function book(){try{const x=await json(`/api/orderbook?worker=1&t=${Date.now()}`),vals=(x.books||[]).map(b=>clamp(+b.imbalance||0,-1,1));return{raw:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0,ready:vals.length>0,count:vals.length}}catch{return{raw:0,ready:false,count:0}}}
async function flow(){try{const x=await json(`/api/live-trades?worker=1&t=${Date.now()}`),a=x.trades||x.data||[];let b=0,s=0;for(const t of a){let usd=+(t.usd||t.value||t.amountUsd||0);if(!usd&&+t.p>0&&+t.q>0)usd=(+t.p)*(+t.q);const side=String(t.side||t.s||'').toLowerCase();if(side==='buy')b+=usd;else if(side==='sell')s+=usd}const total=b+s;return{raw:total?(b-s)/total:0,ready:total>0,usd:total}}catch{return{raw:0,ready:false,usd:0}}}
async function readState(){const u=`https://api.github.com/repos/${OWNER}/${REPO}/contents/${STATE_PATH}?ref=${BRANCH}`,r=await fetch(u,{headers:H});if(r.status===404)return{state:{version:3,history:[],clusters:{},stateMem:[],global:{},systemStats:{}},sha:null};if(!r.ok)throw new Error(`state read ${r.status}`);const x=await r.json();return{state:JSON.parse(Buffer.from(x.content,'base64').toString('utf8')),sha:x.sha}}
async function writeState(state,sha){const u=`https://api.github.com/repos/${OWNER}/${REPO}/contents/${STATE_PATH}`,body={message:'Update unified 24/7 learning state',content:Buffer.from(JSON.stringify(state)).toString('base64'),branch:BRANCH};if(sha)body.sha=sha;const r=await fetch(u,{method:'PUT',headers:{...H,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`state write ${r.status} ${await r.text()}`)}
function regime(s15,s1,s4){const strength=Math.abs(s1.trend)*.55+Math.abs(s4.trend)*.3+Math.abs(s15.trend)*.15;if(strength>1.4&&s1.eff>.28)return'TRENDING';if(Math.abs(s15.breakout)>.82&&Math.abs(s15.momentum)>1.15)return'BREAKOUT';if(s1.vol<.0045&&s1.eff<.25)return'LOW VOLATILITY';if(Math.abs(s1.trend)<.55&&s1.eff<.3)return'RANGING';return'TRANSITION'}
function reliability(stats,name){const s=stats[name]||{n:0,ok:0};const rate=(s.ok+4)/(s.n+8),quality=1-Math.exp(-s.n/20);return{n:s.n||0,rate,quality,score:clamp(.75+((rate-.5)*1.2*quality),.55,1.35)}}
function systemSnapshot(s15,s1,s4,b,f,av,pat,ant,state){const trend=.28*s15.trend+.46*s1.trend+.26*s4.trend,mom=.46*s15.momentum+.39*s1.momentum+.15*s4.momentum;const structure=tern(trend*.62+s1.breakout*.2+s4.breakout*.18,.16),momentum=tern(mom,.18),bookDir=b.ready?tern(b.raw,.06):0,flowDir=f.ready?tern(f.raw,.06):0,avwap=dirNum(av?.direction),pattern=dirNum(pat?.direction);const prev=+state.latest?.antScore||0,antScore=+ant?.score||0,delta=prev?((antScore-prev)/Math.max(1,Math.abs(prev))):0,antDir=tern(delta,.0015);return{trend,mom,systems:{structure,momentum,book:bookDir,flow:flowDir,avwap,pattern,ant:antDir},antScore,antDelta:delta}}
function makeModel(s15,s1,s4,b,f,av,pat,ant,state){const rg=regime(s15,s1,s4),snap=systemSnapshot(s15,s1,s4,b,f,av,pat,ant,state);const base={structure:.22,momentum:.17,book:b.ready?.14:0,flow:f.ready?.14:0,avwap:av?.ok?.16:0,pattern:pat?.ok?.13:0,ant:snap.systems.ant?.04:0};if(rg==='BREAKOUT'){base.structure=.18;base.momentum=.19;base.book=b.ready?.15:0;base.flow=f.ready?.16:0;base.avwap=av?.ok?.16:0;base.pattern=pat?.ok?.14:0}else if(rg==='TRENDING'){base.structure=.29;base.momentum=.18;base.avwap=av?.ok?.18:0;base.pattern=pat?.ok?.12:0}else if(rg==='RANGING'){base.structure=.15;base.momentum=.12;base.book=b.ready?.20:0;base.flow=f.ready?.18:0;base.avwap=av?.ok?.16:0;base.pattern=pat?.ok?.13:0}let score=0,w=0,weights={};for(const [name,bw] of Object.entries(base)){if(!bw)continue;const rel=reliability(state.systemStats,name),ww=bw*rel.score;weights[name]=+ww.toFixed(4);score+=(snap.systems[name]||0)*ww;w+=ww}score/=Math.max(.01,w);score+=clamp(snap.trend*.05,-.12,.12)+clamp(snap.mom*.035,-.08,.08);const prob=1/(1+Math.exp(-2.2*score)),neutral=clamp(32-Math.abs(prob-.5)*44,10,32),up=prob*(100-neutral),down=(1-prob)*(100-neutral),edge=up-down,dir=Math.abs(edge)<14?'NEUTRAL':edge>0?'BULLISH':'BEARISH',conf=Math.round(clamp(Math.max(up,down,neutral),34,88));const states={trend:tern(snap.trend),momentum:tern(snap.mom),flow:snap.systems.flow,book:snap.systems.book,avwap:snap.systems.avwap,pattern:snap.systems.pattern};const cluster=[rg,...Object.values(states)].join('|');return{price:s15.p,dir,conf,cluster,regime:rg,states,systems:snap.systems,weights,up:Math.round(up),down:Math.round(down),neutral:Math.round(neutral),antScore:snap.antScore,antDelta:snap.antDelta}}
function learnSystem(state,name,v,move){if(!v)return;const s=state.systemStats[name]||(state.systemStats[name]={n:0,ok:0,rate:null});s.n++;if((v>0&&move>.001)||(v<0&&move<-.001))s.ok++;s.rate=s.ok/s.n}
function evaluate(state,currentPrice,now){for(const p of state.history||[]){if(p.done||now-p.createdAt<3600000)continue;const move=currentPrice/p.price-1;p.done=true;p.move=move;p.resolvedAt=now;p.correct=p.dir==='BULLISH'?move>.001:p.dir==='BEARISH'?move<-.001:Math.abs(move)<=.001;if(p.dir!=='NEUTRAL'){const c=state.clusters[p.cluster]||(state.clusters[p.cluster]={n:0,ok:0,avg:0});c.n++;if(p.correct)c.ok++;c.avg+=(move-c.avg)/c.n}for(const [name,v] of Object.entries(p.systems||{}))learnSystem(state,name,+v||0,move)}}
const {state,sha}=await readState();state.version=3;state.history=Array.isArray(state.history)?state.history:[];state.clusters=state.clusters||{};state.stateMem=Array.isArray(state.stateMem)?state.stateMem:[];state.systemStats=state.systemStats||{};
const [d15,d1,d4,b,f,av,pat,ant,net]=await Promise.all([candles('15m',320),candles('1h',260),candles('4h',200),book(),flow(),json(`/api/avwap-signal?worker=1&t=${Date.now()}`).catch(()=>({ok:false})),json(`/api/pattern-scan?worker=1&t=${Date.now()}`).catch(()=>({ok:false})),json(`/api/ant-score?worker=1&t=${Date.now()}`).catch(()=>({})),json(`/api/network-status?worker=1&t=${Date.now()}`).catch(()=>({}))]);
const s15=sig(d15),s1=sig(d1),s4=sig(d4);if(!s15||!s1||!s4)throw new Error('insufficient unified candle history');const now=Date.now(),m=makeModel(s15,s1,s4,b,f,av,pat,ant,state);evaluate(state,m.price,now);
const last=state.history.at(-1);if(!last||now-last.createdAt>=14*60*1000)state.history.push({createdAt:now,bucket:Math.floor(now/900000)*900,price:m.price,dir:m.dir,confidence:m.conf,conf:m.conf,cluster:m.cluster,regime:m.regime,states:m.states,systems:m.systems,weights:m.weights,done:false});state.history=state.history.slice(-1500);state.stateMem.push({t:now,regime:m.regime,...m.states,...m.systems});state.stateMem=state.stateMem.slice(-750);
const completed=state.history.filter(x=>x.done&&x.dir!=='NEUTRAL'),correct=completed.filter(x=>x.correct).length;state.global={completed:completed.length,correct,hitRate:completed.length?correct/completed.length:null};state.systemReliability=Object.fromEntries(Object.keys(state.systemStats).map(k=>[k,reliability(state.systemStats,k)]));state.latest={...m,bookReady:b.ready,bookSources:b.count,flowReady:f.ready,flowUsd:f.usd,avwap:{direction:av?.direction||'NEUTRAL',alignment:+av?.alignment||0,strength:+av?.strength||0},pattern:{direction:pat?.direction||'NEUTRAL',alignment:+pat?.alignment||0,strongest:pat?.strongest||null},network:{healthy:!!net?.ok,tick:+net?.tick||+net?.currentTick||0},dataMode:'UNIFIED_STRUCTURE_NO_EMA'};state.updatedAt=new Date(now).toISOString();state.runCount=(state.runCount||0)+1;await writeState(state,sha);console.log(`Unified learner ${state.updatedAt} dir=${m.dir} conf=${m.conf}% systems=${Object.keys(m.systems).length} completed=${completed.length}`);