let cache={ts:0,chosen:null,scores:{}};
const timeout=(p,ms=5200)=>Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(new Error('timeout')),ms))]);
const get=async u=>{const r=await timeout(fetch(u,{cache:'no-store',headers:{accept:'application/json','user-agent':'QubicLiveChart/5.3'}}));if(!r.ok)throw Error(String(r.status));return r.json()};
const normTs=t=>{t=+t||0;return t<1e12?t*1000:t};
const scoreRows=(rows,now)=>{let usd=0,n=0,last=0;for(const x of rows){const t=normTs(x.t),p=+x.p,q=+x.q;if(t>=now-120000&&p>0&&q>0){usd+=p*q;n++;last=Math.max(last,t)}}return {usd,n,last,score:usd*(1+Math.min(n,80)/80)*(last>now-20000?1.15:1)}};
async function activity(){const now=Date.now();if(now-cache.ts<15000&&cache.chosen)return cache;const rows={GATE:[],MEXC:[],BITGET:[],COINEX:[],LBANK:[]};const push=(ex,p,q,t)=>rows[ex].push({p:+p,q:+q,t:normTs(t)});await Promise.allSettled([
get('https://api.gateio.ws/api/v4/spot/trades?currency_pair=QUBIC_USDT&limit=100').then(a=>a.forEach(x=>push('GATE',x.price,x.amount,x.create_time_ms||x.create_time))),
get('https://api.mexc.com/api/v3/trades?symbol=QUBICUSDT&limit=100').then(a=>a.forEach(x=>push('MEXC',x.price,x.qty,x.time))),
get('https://api.bitget.com/api/v2/spot/market/fills?symbol=QUBICUSDT&limit=100').then(x=>(x.data||[]).forEach(v=>push('BITGET',v.price||v.px,v.size||v.sz,v.ts||v.time))),
get('https://api.coinex.com/v2/spot/deals?market=QUBICUSDT&limit=100').then(x=>(x.data||[]).forEach(v=>push('COINEX',v.price,v.amount,v.created_at||v.createdAt||v.time))),
get('https://api.lbkex.com/v2/trades.do?symbol=qubic_usdt&size=100').then(x=>(x.data||[]).forEach(v=>push('LBANK',v.price,v.amount||v.volume,v.date_ms||v.date||v.time)))
]);const scores={};for(const [k,v] of Object.entries(rows))scores[k]=scoreRows(v,now);const ranked=Object.entries(scores).sort((a,b)=>b[1].score-a[1].score);cache={ts:now,chosen:ranked[0]?.[0]||'GATE',scores};return cache}
const maps={GATE:{'1m':'1m','5m':'5m','15m':'15m','30m':'30m','1h':'1h','4h':'4h','1d':'1d'},MEXC:{'1m':'1m','5m':'5m','15m':'15m','30m':'30m','1h':'60m','4h':'4h','1d':'1d'},BITGET:{'1m':'1min','5m':'5min','15m':'15min','30m':'30min','1h':'1h','4h':'4h','1d':'1day'},COINEX:{'1m':'1min','5m':'5min','15m':'15min','30m':'30min','1h':'1hour','4h':'4hour','1d':'1day'},LBANK:{'1m':'minute1','5m':'minute5','15m':'minute15','30m':'minute30','1h':'hour1','4h':'hour4','1d':'day1'}};
const sec={'1m':60,'5m':300,'15m':900,'30m':1800,'1h':3600,'4h':14400,'1d':86400};
async function candles(ex,iv,limit){if(ex==='GATE'){const a=await get(`https://api.gateio.ws/api/v4/spot/candlesticks?currency_pair=QUBIC_USDT&interval=${maps.GATE[iv]}&limit=${limit}`);return a.map(x=>({time:+x[0],open:+x[5],high:+x[3],low:+x[4],close:+x[2],volume:+x[1]||0}))}if(ex==='MEXC'){const a=await get(`https://api.mexc.com/api/v3/klines?symbol=QUBICUSDT&interval=${maps.MEXC[iv]}&limit=${limit}`);return a.map(x=>({time:Math.floor(+x[0]/1000),open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[5]||0}))}if(ex==='BITGET'){const x=await get(`https://api.bitget.com/api/v2/spot/market/candles?symbol=QUBICUSDT&granularity=${maps.BITGET[iv]}&limit=${Math.min(limit,1000)}`);return (x.data||[]).map(v=>({time:Math.floor(+v[0]/1000),open:+v[1],high:+v[2],low:+v[3],close:+v[4],volume:+v[5]||0}))}if(ex==='COINEX'){const x=await get(`https://api.coinex.com/v2/spot/kline?market=QUBICUSDT&period=${maps.COINEX[iv]}&limit=${Math.min(limit,1000)}`);return (x.data||[]).map(v=>({time:Math.floor(+(v.created_at||v.createdAt)/1000),open:+v.open,high:+v.high,low:+v.low,close:+v.close,volume:+v.volume||0}))}if(ex==='LBANK'){const start=Math.floor(Date.now()/1000)-Math.min(limit,2000)*sec[iv];const x=await get(`https://api.lbank.info/v2/kline.do?symbol=qubic_usdt&size=${Math.min(limit,2000)}&type=${maps.LBANK[iv]}&time=${start}`);return (x.data||[]).map(v=>({time:+v[0],open:+v[1],high:+v[2],low:+v[3],close:+v[4],volume:+v[5]||0}))}return []}
const median=a=>{const x=a.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return NaN;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
function composite(feeds,limit){const by=new Map();for(const [ex,rows] of Object.entries(feeds))for(const c of rows){const t=Math.floor(c.time/3600)*3600;if(!by.has(t))by.set(t,[]);by.get(t).push({...c,ex})}const out=[];for(const [time,rows] of [...by.entries()].sort((a,b)=>a[0]-b[0])){if(rows.length<2)continue;const closes=rows.map(x=>x.close),m=median(closes),mad=median(closes.map(x=>Math.abs(x-m))),agreement=Math.max(0,1-Math.min(1,(mad/(m||1))*250));out.push({time,open:median(rows.map(x=>x.open)),high:median(rows.map(x=>x.high)),low:median(rows.map(x=>x.low)),close:m,volume:rows.reduce((s,x)=>s+(x.volume||0),0),sources:rows.length,agreement})}return out.slice(-limit)}
async function compositeFeed(limit=1000){const names=['GATE','MEXC','BITGET','COINEX'];const settled=await Promise.allSettled(names.map(ex=>candles(ex,'1h',limit))),feeds={},errors={};settled.forEach((r,i)=>{const ex=names[i];if(r.status==='fulfilled'){const d=(r.value||[]).filter(x=>Number.isFinite(x.time)&&x.open>0&&x.high>0&&x.low>0&&x.close>0).sort((x,y)=>x.time-y.time);if(d.length>=120)feeds[ex]=d;else errors[ex]=`only ${d.length} candles`}else errors[ex]=String(r.reason?.message||r.reason)});return {data:composite(feeds,limit),feeds,errors}}

// Raw V4.3: BPP9000-style recurrent ternary core with multi-horizon populations,
// weighted walk-forward fitness, survivor diversity, empirical calibration and regime-aware weighting.
// The public BPP9000 structural mechanics are mirrored, but QUBIC encoding/topology remain custom.
const VP=64,VI=18,VO=18,VS=19,VL=27,VM=100,VUNK=2,VSURV=451;
const HORIZONS=[168,336,672],ROOTS_PER_H=4,CANDIDATES_PER_H=180;
function h32(a,b){let x=(a^Math.imul((b+0x9e3779b9)|0,0x85ebca6b))>>>0;x=Math.imul(x^(x>>>16),0x7feb352d);x=Math.imul(x^(x>>>15),0x846ca68b);return(x^(x>>>16))>>>0}
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:0}function sd(a){const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)*(x-m))))||1e-12}function t3(v,t){return v>t?1:v<-t?0:2}
function featureRows(c){const out=[];for(let i=0;i<c.length;i++){if(i<49){out.push(new Uint8Array(VI).fill(2));continue}const r=[];for(let k=Math.max(1,i-96);k<=i;k++)r.push(Math.log(c[k].close/c[k-1].close));const abs=r.map(Math.abs).sort((a,b)=>a-b),sc=Math.max(abs[Math.floor(abs.length/2)]*1.7,1e-12),v=[];for(const lag of[1,2,3,4,6,8,12,18])v.push(t3(r.at(-lag)||0,sc*.2));for(const n of[3,6,12,24])v.push(t3(mean(r.slice(-n)),sc*.12));v.push(t3(mean(r.slice(-48)),sc*.08));const q=c[i],body=(q.close-q.open)/q.open,range=(q.high-q.low)/q.open;v.push(t3(body,sc*.45));const ranges=c.slice(i-24,i+1).map(x=>(x.high-x.low)/x.open).sort((a,b)=>a-b);v.push(t3(range-ranges[Math.floor(ranges.length/2)],sc*.3));const vv=c.slice(i-48,i+1).map(x=>Math.log(1+(x.volume||0))),z=(Math.log(1+(q.volume||0))-mean(vv))/sd(vv);v.push(t3(z,.35));const cls=c.slice(i-24,i+1).map(x=>x.close).sort((a,b)=>a-b);v.push(t3((q.close-cls[Math.floor(cls.length/2)])/q.close,sc*2));v.push(q.agreement>.82?1:q.agreement<.55?0:2);out.push(Uint8Array.from(v.slice(0,18)))}return out}
function makeVAnn(seed){const neigh=new Uint8Array(VP*3),lut=new Uint8Array(VP*VL);for(let n=0;n<VP;n++){for(let j=0;j<3;j++)neigh[n*3+j]=h32(seed+n*131,j+17)%VP;for(let l=0;l<VL;l++)lut[n*VL+l]=h32(seed+n*911,l+71)%3}return{seed,neigh,lut}}
function cloneV(a){return{seed:a.seed,neigh:a.neigh,lut:new Uint8Array(a.lut)}}
function inferWindow(a,fr,start,width,maxTicks=6500){const st=new Uint8Array(VP),nx=new Uint8Array(VP);st.fill(VUNK);let feed=0,tick=0;for(;tick<maxTicks;tick++){if(st[VS]===VUNK){if(feed>=width)break;const row=fr[start+feed];for(let i=0;i<VI;i++)st[i]=row[i];feed++}else for(let i=0;i<VI;i++)st[i]=VUNK;for(let i=0;i<VI;i++)nx[i]=st[i];for(let n=VI;n<VP;n++){const k=n*3,idx=st[a.neigh[k]]+3*st[a.neigh[k+1]]+9*st[a.neigh[k+2]];nx[n]=a.lut[n*VL+idx]}for(let n=VI;n<VP;n++)st[n]=nx[n]}return tick>=maxTicks?VUNK:st[VO]}
function mutateV(a,seed,L=2){for(let j=0;j<L;j++){const r=((h32(seed,j+101)>>>1)%((VP-VI)*VL))>>>0,n=VI+Math.floor(r/VL),line=r%VL,ix=n*VL+line,delta=h32(seed,j+301)&1;a.lut[ix]=(a.lut[ix]+1+delta)%3}}
function scoreV(a,fr,c,ends,width){let e=0,tw=0;for(let i=0;i<ends.length;i++){const end=ends[i],w=Math.max(.75,1.55-i*.16),p=inferWindow(a,fr,end-width+1,width),y=c[end+1].close>=c[end].close?1:0;tw+=w;if(p===VUNK||p!==y)e+=w}return e/(tw||1)}
function walkV(root,fr,c,ends,width,seed){let cur=cloneV(root),curS=scoreV(cur,fr,c,ends,width),best=cloneV(cur),bestS=curS,accepted=0;for(let s=0;s<VM;s++){const prev=new Uint8Array(cur.lut);mutateV(cur,h32(seed,s+700),2);const r=scoreV(cur,fr,c,ends,width);if(r<=curS){curS=r;accepted++}else cur.lut=prev;if(curS<bestS){bestS=curS;best=cloneV(cur)}}return{ann:best,start:scoreV(root,fr,c,ends,width),best:bestS,accepted}}
function voteSet(models,fr,end,width){let u=0,d=0,x=0;for(const s of models){const v=inferWindow(s.ann||s,fr,end-width+1,width);v===1?u++:v===0?d++:x++}return{u,d,x}}
function fingerprint(model,fr,ends,width){let s='';for(const e of ends){const v=inferWindow(model.ann||model,fr,e-width+1,width);s+=String(v)}return s}
function diversitySelect(candidates,fr,evalEnds,width,limit){candidates.sort((a,b)=>a.score-b.score||b.depth-a.depth);const out=[],seen=new Map();for(const c of candidates){const fp=fingerprint(c,fr,evalEnds,width),n=seen.get(fp)||0;if(n>=5)continue;seen.set(fp,n+1);out.push(c);if(out.length>=limit)break}if(out.length<limit){for(const c of candidates){if(out.includes(c))continue;out.push(c);if(out.length>=limit)break}}return out}
function regimeOf(c,end){const ret=(n)=>Math.log(c[end].close/c[Math.max(0,end-n)].close);const r6=ret(6),r24=ret(24),rs=[];for(let i=Math.max(1,end-24);i<=end;i++)rs.push(Math.log(c[i].close/c[i-1].close));const vol=sd(rs),base=Math.max(mean(rs.map(Math.abs)),1e-12);if(r6>base*2&&r24>0)return 'BULLISH';if(r6<-base*2&&r24<0)return 'BEARISH';if(vol>base*2.1)return 'HIGH_VOL';return 'MIXED'}
function calibrate(models,fr,c,width,last){const ends=[];for(let e=last-2;e>=width-1&&ends.length<12;e-=2)ends.push(e);let n=0,w=0,upN=0,upW=0,dnN=0,dnW=0,marginSum=0;for(const e of ends){const v=voteSet(models,fr,e,width),dir=v.u+v.d;if(!dir||v.u===v.d)continue;const pred=v.u>v.d?1:0,y=c[e+1].close>=c[e].close?1:0,m=Math.abs(v.u-v.d)/dir;n++;marginSum+=m;if(pred===y)w++;if(pred===1){upN++;if(pred===y)upW++}else{dnN++;if(pred===y)dnW++}}return{accuracy:n?w/n:.5,n,upAccuracy:upN?upW/upN:.5,downAccuracy:dnN?dnW/dnN:.5,meanMargin:n?marginSum/n:0}}
function trainHorizon(c,fr,width,hix){const last=c.length-2,trainEnd=Math.max(width-1,last-16),ends=[];for(let e=trainEnd;e>=width-1&&ends.length<5;e-=Math.max(6,Math.floor(width/56)))ends.push(e);const roots=[],cand=[];let gain=0,accepted=0;for(let r=0;r<ROOTS_PER_H;r++){const seed=h32(20260903+hix*1000,r+1),root=makeVAnn(seed),w=walkV(root,fr,c,ends,width,h32(seed,900));gain+=w.start-w.best;accepted+=w.accepted;roots.push(w.ann);cand.push({ann:w.ann,score:w.best,depth:1,horizon:width});let parent=w.ann,ps=w.best;for(let depth=2;depth<=5;depth++){const child=cloneV(parent);for(let k=0;k<5;k++)mutateV(child,h32(seed+depth*97,k+5000),2);const sc=scoreV(child,fr,c,ends,width);if(sc<=ps){parent=child;ps=sc}cand.push({ann:parent,score:ps,depth,horizon:width})}}
let n=0;while(cand.length<CANDIDATES_PER_H){const base=roots[n%roots.length],child=cloneV(base),depth=2+(n%4);for(let d=0;d<depth;d++)mutateV(child,h32(12000+hix*5000+n,d+3),2);cand.push({ann:child,score:scoreV(child,fr,c,ends,width),depth,horizon:width});n++}const evalEnds=[];for(let e=last-3;e>=width-1&&evalEnds.length<8;e-=3)evalEnds.push(e);const keep=Math.floor(VSURV/HORIZONS.length)+(hix<VSURV%HORIZONS.length?1:0),survivors=diversitySelect(cand,fr,evalEnds,width,keep),cal=calibrate(survivors,fr,c,width,last);return{width,survivors,cal,gain:gain/ROOTS_PER_H,accepted:accepted/ROOTS_PER_H,trainWindows:ends.length,maxDepth:Math.max(...survivors.map(x=>x.depth))}}
function trainV43(c){if(c.length<672+110)throw Error('V4.3 requires at least 782 overlapping hourly candles');const fr=featureRows(c),groups=HORIZONS.map((w,i)=>trainHorizon(c,fr,w,i));return{fr,groups}}
function predictV43(c,t){const end=c.length-2,regime=regimeOf(c,end);let weightedUp=0,weightedDown=0,totalWeight=0,rawU=0,rawD=0,rawX=0;const horizons=[];for(const g of t.groups){const v=voteSet(g.survivors,t.fr,end,g.width),dir=v.u+v.d,margin=dir?Math.abs(v.u-v.d)/dir:0;let edge=(g.cal.accuracy-.5)*2,weight=Math.max(.35,Math.min(1.8,1+edge*3));if(regime==='HIGH_VOL'&&g.width===168)weight*=1.15;if(regime==='BULLISH'||regime==='BEARISH'){if(g.width===336)weight*=1.08}if(g.cal.n<5)weight*=.8;rawU+=v.u;rawD+=v.d;rawX+=v.x;if(dir){weightedUp+=weight*(v.u/dir);weightedDown+=weight*(v.d/dir);totalWeight+=weight}horizons.push({hours:g.width,u:v.u,d:v.d,x:v.x,margin,walkForwardAccuracy:g.cal.accuracy,walkForwardN:g.cal.n,weight})}
const pu=totalWeight?weightedUp/totalWeight:.5,pd=totalWeight?weightedDown/totalWeight:.5,margin=Math.abs(pu-pd),agr=c[end].agreement||0,avgAcc=mean(t.groups.map(g=>g.cal.accuracy));let conf=.5+Math.min(.18,margin*.55)+Math.max(-.04,Math.min(.08,(avgAcc-.5)*.6));conf=Math.max(.5,Math.min(.78,conf));let signal=pu>pd?'UP_OR_FLAT':pd>pu?'DOWN':'UNKNOWN';if(margin<.045||agr<.55||conf<.525||avgAcc<.49)signal='UNKNOWN';const best=horizons.slice().sort((a,b)=>b.walkForwardAccuracy-a.walkForwardAccuracy)[0];return{signal,u:rawU,d:rawD,x:rawX,confidence:conf,margin,agreement:agr,base:c[end].close,target:(c[end].time+3600)*1000,regime,weightedUp:pu,weightedDown:pd,horizons,bestHorizon:best?.hours||null,walkForwardAccuracy:avgAcc}}

module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store, max-age=0');res.setHeader('Access-Control-Allow-Origin','*');const iv=['1m','5m','15m','30m','1h','4h','1d'].includes(String(req.query?.interval))?String(req.query.interval):'15m';const limit=Math.max(60,Math.min(1000,+req.query?.limit||480));const prefer=String(req.query?.prefer||'').toUpperCase(),useComposite=String(req.query?.composite||'')==='1'&&iv==='1h',useV4=String(req.query?.v4||'')==='1';try{const a=await activity();if(useV4){const f=await compositeFeed(1000);if(f.data.length<782)return res.status(503).json({ok:false,error:'Not enough overlapping composite history for V4.3',candles:f.data.length,required:782,errors:f.errors,ts:Date.now()});const started=Date.now(),t=trainV43(f.data),p=predictV43(f.data,t);return res.status(200).json({ok:true,version:'V4.3',source:'MULTI-EXCHANGE MEDIAN',exchanges:Object.keys(f.feeds),candles:f.data.length,prediction:p,engine:{population:VP,inputNeurons:VI,outputNeurons:1,signalNeurons:1,neighbors:3,lutEntries:VL,horizons:HORIZONS,mutationSteps:VM,lutEditsPerStep:2,rootsPerHorizon:ROOTS_PER_H,survivors:VSURV,trainWindows:t.groups.reduce((s,g)=>s+g.trainWindows,0),maxDepth:Math.max(...t.groups.map(g=>g.maxDepth)),meanAcceptedMutations:+mean(t.groups.map(g=>g.accepted)).toFixed(1),meanMutationGain:+mean(t.groups.map(g=>g.gain)).toFixed(3),walkForwardAccuracy:p.walkForwardAccuracy,survivorDiversity:true,regimeAware:true,empiricalCalibration:true,weightedRecentFitness:true,encoding:'custom QUBIC 18-trit features',selfClocked:true,bitExactMainnet:false},latest:f.data.at(-1),series:f.data.slice(-168).map(x=>({time:x.time,close:x.close,agreement:x.agreement})),elapsedMs:Date.now()-started,errors:f.errors,ts:Date.now()})}
if(useComposite){const f=await compositeFeed(limit),data=f.data;if(data.length<250)return res.status(503).json({ok:false,error:'Not enough overlapping composite history',counts:Object.fromEntries(Object.entries(f.feeds).map(([k,v])=>[k,v.length])),errors:f.errors,ts:Date.now()});return res.status(200).json({ok:true,interval:'1h',source:'MULTI-EXCHANGE MEDIAN',exchanges:Object.keys(f.feeds),activity:a.scores,errors:f.errors,candles:data,latestAgreement:data.at(-1)?.agreement??null,ts:Date.now()})}
const ranked=Object.entries(a.scores).sort((x,y)=>y[1].score-x[1].score);let chosen=a.chosen;const top=ranked[0]?.[1]?.score||0;if(prefer&&a.scores[prefer]&&a.scores[prefer].score>=top*.65)chosen=prefer;const order=[chosen,...ranked.map(x=>x[0]),'GATE'].filter((v,i,s)=>v&&s.indexOf(v)===i);let data=[],source=null;const minHistory=Math.min(80,Math.max(40,Math.floor(limit*.15))),rejected={};for(const ex of order){try{const d=(await candles(ex,iv,limit)).filter(x=>Number.isFinite(x.time)&&x.open>0&&x.high>0&&x.low>0&&x.close>0).sort((x,y)=>x.time-y.time);if(d.length>=minHistory){data=d;source=ex;break}rejected[ex]=d.length}catch(e){rejected[ex]=String(e?.message||e)}}if(!data.length)return res.status(503).json({ok:false,error:'No active exchange has enough candle history',interval:iv,minHistory,rejected,ts:Date.now()});res.status(200).json({ok:true,interval:iv,source,activity:a.scores,minHistory,rejected,candles:data,ts:Date.now()})}catch(e){res.status(503).json({ok:false,error:String(e?.message||e),interval:iv,ts:Date.now()})}}
