let cache={ts:0,chosen:null,scores:{}};
const timeout=(p,ms=5200)=>Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(new Error('timeout')),ms))]);
const get=async u=>{const r=await timeout(fetch(u,{cache:'no-store',headers:{accept:'application/json','user-agent':'QubicLiveChart/4.0'}}));if(!r.ok)throw Error(String(r.status));return r.json()};
const normTs=t=>{t=+t||0;return t<1e12?t*1000:t};
const scoreRows=(rows,now)=>{let usd=0,n=0,last=0;for(const x of rows){const t=normTs(x.t),p=+x.p,q=+x.q;if(t>=now-120000&&p>0&&q>0){usd+=p*q;n++;last=Math.max(last,t)}}return {usd,n,last,score:usd*(1+Math.min(n,80)/80)*(last>now-20000?1.15:1)}};
async function activity(){const now=Date.now();if(now-cache.ts<15000&&cache.chosen)return cache;const rows={GATE:[],MEXC:[],BITGET:[],COINEX:[],LBANK:[]};const push=(ex,p,q,t)=>rows[ex].push({p:+p,q:+q,t:normTs(t)});await Promise.allSettled([
get('https://api.gateio.ws/api/v4/spot/trades?currency_pair=QUBIC_USDT&limit=100').then(a=>a.forEach(x=>push('GATE',x.price,x.amount,x.create_time_ms||x.create_time))),
get('https://api.mexc.com/api/v3/trades?symbol=QUBICUSDT&limit=100').then(a=>a.forEach(x=>push('MEXC',x.price,x.qty,x.time))),
get('https://api.bitget.com/api/v2/spot/market/fills?symbol=QUBICUSDT&limit=100').then(x=>(x.data||[]).forEach(v=>push('BITGET',v.price||v.px,v.size||v.sz,v.ts||v.time))),
get('https://api.coinex.com/v2/spot/deals?market=QUBICUSDT&limit=100').then(x=>(x.data||[]).forEach(v=>push('COINEX',v.price,v.amount,v.created_at||v.createdAt||v.time))),
get('https://api.lbkex.com/v2/trades.do?symbol=qubic_usdt&size=100').then(x=>(x.data||[]).forEach(v=>push('LBANK',v.price,v.amount||v.volume,v.date_ms||v.date||v.time)))
]);const scores={};for(const [k,v] of Object.entries(rows))scores[k]=scoreRows(v,now);const ranked=Object.entries(scores).sort((a,b)=>b[1].score-a[1].score);cache={ts:now,chosen:ranked[0]?.[0]||'GATE',scores};return cache}
const maps={GATE:{'1m':'1m','5m':'5m','15m':'15m','30m':'30m','1h':'1h','4h':'4h','1d':'1d'},MEXC:{'1m':'1m','5m':'5m','15m':'15m','30m':'30m','1h':'60m','4h':'4h','1d':'1d'},BITGET:{'1m':'1min','5m':'5min','15m':'15min','30m':'30min','1h':'1h','4h':'4h','1d':'1day'},COINEX:{'1m':'1min','5m':'5min','15m':'15min','30m':'30min','1h':'1hour','4h':'4hour','1d':'1day'},LBANK:{'1m':'minute1','5m':'minute5','15m':'minute15','30m':'minute30','1h':'hour1','4h':'hour4','1d':'day1'}};
const sec={'1m':60,'5m':300,'15m':900,'30m':1800,'1h':3600,'4h':14400,'1d':86400};
async function candles(ex,iv,limit){if(ex==='GATE'){const a=await get(`https://api.gateio.ws/api/v4/spot/candlesticks?currency_pair=QUBIC_USDT&interval=${maps.GATE[iv]}&limit=${limit}`);return a.map(x=>({time:+x[0],open:+x[5],high:+x[3],low:+x[4],close:+x[2],volume:+x[1]||0}))}if(ex==='MEXC'){const a=await get(`https://api.mexc.com/api/v3/klines?symbol=QUBICUSDT&interval=${maps.MEXC[iv]}&limit=${limit}`);return a.map(x=>({time:Math.floor(+x[0]/1000),open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[5]||0}))}if(ex==='BITGET'){const x=await get(`https://api.bitget.com/api/v2/spot/market/candles?symbol=QUBICUSDT&granularity=${maps.BITGET[iv]}&limit=${Math.min(limit,1000)}`);return (x.data||[]).map(v=>({time:Math.floor(+v[0]/1000),open:+v[1],high:+v[2],low:+v[3],close:+v[4],volume:+v[5]||0}))}if(ex==='COINEX'){const x=await get(`https://api.coinex.com/v2/spot/kline?market=QUBICUSDT&period=${maps.COINEX[iv]}&limit=${Math.min(limit,1000)}`);return (x.data||[]).map(v=>({time:Math.floor(+(v.created_at||v.createdAt)/1000),open:+v.open,high:+v.high,low:+v.low,close:+v.close,volume:+v.volume||0}))}if(ex==='LBANK'){const start=Math.floor(Date.now()/1000)-Math.min(limit,2000)*sec[iv];const x=await get(`https://api.lbank.info/v2/kline.do?symbol=qubic_usdt&size=${Math.min(limit,2000)}&type=${maps.LBANK[iv]}&time=${start}`);return (x.data||[]).map(v=>({time:+v[0],open:+v[1],high:+v[2],low:+v[3],close:+v[4],volume:+v[5]||0}))}return []}
const median=a=>{const x=a.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return NaN;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
function composite(feeds,limit){const by=new Map();for(const [ex,rows] of Object.entries(feeds))for(const c of rows){const t=Math.floor(c.time/3600)*3600;if(!by.has(t))by.set(t,[]);by.get(t).push({...c,ex})}const out=[];for(const [time,rows] of [...by.entries()].sort((a,b)=>a[0]-b[0])){if(rows.length<2)continue;const closes=rows.map(x=>x.close),m=median(closes),mad=median(closes.map(x=>Math.abs(x-m))),agreement=Math.max(0,1-Math.min(1,(mad/(m||1))*250));out.push({time,open:median(rows.map(x=>x.open)),high:median(rows.map(x=>x.high)),low:median(rows.map(x=>x.low)),close:m,volume:rows.reduce((s,x)=>s+(x.volume||0),0),sources:rows.length,agreement})}return out.slice(-limit)}
async function compositeFeed(limit=1000){const names=['GATE','MEXC','BITGET','COINEX'];const settled=await Promise.allSettled(names.map(ex=>candles(ex,'1h',limit))),feeds={},errors={};settled.forEach((r,i)=>{const ex=names[i];if(r.status==='fulfilled'){const d=(r.value||[]).filter(x=>Number.isFinite(x.time)&&x.open>0&&x.high>0&&x.low>0&&x.close>0).sort((x,y)=>x.time-y.time);if(d.length>=120)feeds[ex]=d;else errors[ex]=`only ${d.length} candles`}else errors[ex]=String(r.reason?.message||r.reason)});return {data:composite(feeds,limit),feeds,errors}}

// V4 BPP9000-style backend scorer. Structural mechanics mirror the public reference scorer:
// 64 ternary neurons, 18 fixed inputs, 1 output, 1 signal neuron, 3-neighbour 27-entry LUT,
// self-clocked 672-sample feeding and 100-step LUT mutation walks. QUBIC input encoding/topology are custom.
const VP=64,VI=18,VO=18,VS=19,VW=672,VL=27,VM=100,VUNK=2,VROOTS=12,VSURV=451;
function h32(a,b){let x=(a^Math.imul((b+0x9e3779b9)|0,0x85ebca6b))>>>0;x=Math.imul(x^(x>>>16),0x7feb352d);x=Math.imul(x^(x>>>15),0x846ca68b);return(x^(x>>>16))>>>0}
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:0}function sd(a){const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)*(x-m))))||1e-12}function t3(v,t){return v>t?1:v<-t?0:2}
function featureRows(c){const out=[];for(let i=0;i<c.length;i++){if(i<49){out.push(new Uint8Array(VI).fill(2));continue}const r=[];for(let k=Math.max(1,i-80);k<=i;k++)r.push(Math.log(c[k].close/c[k-1].close));const abs=r.map(Math.abs).sort((a,b)=>a-b),sc=Math.max(abs[Math.floor(abs.length/2)]*1.7,1e-12),v=[];for(const lag of[1,2,3,4,6,8,12,18])v.push(t3(r.at(-lag)||0,sc*.2));for(const n of[3,6,12,24])v.push(t3(mean(r.slice(-n)),sc*.12));v.push(t3(mean(r.slice(-48)),sc*.08));const q=c[i],body=(q.close-q.open)/q.open,range=(q.high-q.low)/q.open;v.push(t3(body,sc*.45));const ranges=c.slice(i-24,i+1).map(x=>(x.high-x.low)/x.open).sort((a,b)=>a-b);v.push(t3(range-ranges[Math.floor(ranges.length/2)],sc*.3));const vv=c.slice(i-48,i+1).map(x=>Math.log(1+(x.volume||0))),z=(Math.log(1+(q.volume||0))-mean(vv))/sd(vv);v.push(t3(z,.35));const cls=c.slice(i-24,i+1).map(x=>x.close).sort((a,b)=>a-b);v.push(t3((q.close-cls[Math.floor(cls.length/2)])/q.close,sc*2));v.push(q.agreement>.82?1:q.agreement<.55?0:2);out.push(Uint8Array.from(v.slice(0,18)))}return out}
function makeVAnn(seed){const neigh=new Uint8Array(VP*3),lut=new Uint8Array(VP*VL);for(let n=0;n<VP;n++){for(let j=0;j<3;j++)neigh[n*3+j]=h32(seed+n*131,j+17)%VP;for(let l=0;l<VL;l++)lut[n*VL+l]=h32(seed+n*911,l+71)%3}return{seed,neigh,lut}}
function cloneV(a){return{seed:a.seed,neigh:a.neigh,lut:new Uint8Array(a.lut)}}
function inferWindow(a,fr,start,width=VW,maxTicks=6000){const st=new Uint8Array(VP),nx=new Uint8Array(VP);st.fill(VUNK);let feed=0,tick=0;for(;tick<maxTicks;tick++){if(st[VS]===VUNK){if(feed>=width)break;const row=fr[start+feed];for(let i=0;i<VI;i++)st[i]=row[i];feed++}else for(let i=0;i<VI;i++)st[i]=VUNK;for(let i=0;i<VI;i++)nx[i]=st[i];for(let n=VI;n<VP;n++){const k=n*3,idx=st[a.neigh[k]]+3*st[a.neigh[k+1]]+9*st[a.neigh[k+2]];nx[n]=a.lut[n*VL+idx]}for(let n=VI;n<VP;n++)st[n]=nx[n]}return tick>=maxTicks?VUNK:st[VO]}
function mutateV(a,seed,L=2){for(let j=0;j<L;j++){const r=((h32(seed,j+101)>>>1)%((VP-VI)*VL))>>>0,n=VI+Math.floor(r/VL),line=r%VL,ix=n*VL+line,delta=h32(seed,j+301)&1;a.lut[ix]=(a.lut[ix]+1+delta)%3}}
function scoreV(a,fr,c,ends){let e=0;for(const end of ends){const p=inferWindow(a,fr,end-VW+1),y=c[end+1].close>=c[end].close?1:0;if(p===VUNK||p!==y)e++}return e}
function walkV(root,fr,c,ends,seed){let cur=cloneV(root),curS=scoreV(cur,fr,c,ends),best=cloneV(cur),bestS=curS,accepted=0;for(let s=0;s<VM;s++){const prev=new Uint8Array(cur.lut);mutateV(cur,h32(seed,s+700),2);const r=scoreV(cur,fr,c,ends);if(r<=curS){curS=r;accepted++}else cur.lut=prev;if(curS<bestS){bestS=curS;best=cloneV(cur)}}return{ann:best,start:scoreV(root,fr,c,ends),best:bestS,accepted}}
function trainV4(c){if(c.length<VW+110)throw Error(`V4 requires at least ${VW+110} overlapping hourly candles`);const fr=featureRows(c),last=c.length-2,holdEnd=last-1,trainEnd=Math.max(VW-1,last-30),ends=[];for(let e=trainEnd;e>=VW-1&&ends.length<3;e-=10)ends.push(e);if(!ends.length)ends.push(VW-1);const roots=[],lineages=[];let gain=0,acc=0;for(let r=0;r<VROOTS;r++){const root=makeVAnn(h32(20260903,r+1)),w=walkV(root,fr,c,ends,h32(r+900,17));gain+=w.start-w.best;acc+=w.accepted;roots.push(w.ann);lineages.push({ann:w.ann,score:w.best,depth:1});let parent=w.ann;for(let d=2;d<=5;d++){const child=cloneV(parent);for(let k=0;k<6;k++)mutateV(child,h32(r*97+d*13,k+5000),2);const sc=scoreV(child,fr,c,ends);if(sc<=lineages.at(-1).score){parent=child;lineages.push({ann:child,score:sc,depth:d})}else lineages.push({ann:parent,score:lineages.at(-1).score,depth:d})}}
let n=0;while(lineages.length<VSURV){const base=roots[n%roots.length],child=cloneV(base),depth=2+(n%4);for(let d=0;d<depth;d++)mutateV(child,h32(n+12000,d+3),2);lineages.push({ann:child,score:scoreV(child,fr,c,ends),depth});n++}lineages.sort((a,b)=>a.score-b.score||b.depth-a.depth);const survivors=lineages.slice(0,VSURV);let holdN=0,holdW=0;for(const end of [holdEnd]){if(end<VW-1)continue;let u=0,d=0;for(const s of survivors){const v=inferWindow(s.ann,fr,end-VW+1);v===1?u++:v===0?d++:0}if(u!==d){holdN++;if((u>d)===(c[end+1].close>=c[end].close))holdW++}}return{fr,survivors,hold:holdN?holdW/holdN:.5,gain:gain/VROOTS,accepted:acc/VROOTS,trainWindows:ends.length,maxDepth:Math.max(...survivors.map(x=>x.depth))}}
function predictV4(c,t){const end=c.length-2,start=end-VW+1;let u=0,d=0,x=0;for(const s of t.survivors){const v=inferWindow(s.ann,t.fr,start);v===1?u++:v===0?d++:x++}const dn=u+d,margin=dn?Math.abs(u-d)/dn:0,agr=c[end].agreement||0;let conf=.5+Math.min(.22,margin*.42);if(t.hold>.5)conf+=Math.min(.06,(t.hold-.5)*.2);conf=Math.min(.79,conf);let signal=u>d?'UP_OR_FLAT':d>u?'DOWN':'UNKNOWN';if(margin<.055||agr<.52||conf<.53)signal='UNKNOWN';return{signal,u,d,x,confidence:conf,margin,agreement:agr,base:c[end].close,target:(c[end].time+3600)*1000}}

module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store, max-age=0');res.setHeader('Access-Control-Allow-Origin','*');const iv=['1m','5m','15m','30m','1h','4h','1d'].includes(String(req.query?.interval))?String(req.query.interval):'15m';const limit=Math.max(60,Math.min(1000,+req.query?.limit||480));const prefer=String(req.query?.prefer||'').toUpperCase(),useComposite=String(req.query?.composite||'')==='1'&&iv==='1h',useV4=String(req.query?.v4||'')==='1';try{const a=await activity();if(useV4){const f=await compositeFeed(1000);if(f.data.length<VW+110)return res.status(503).json({ok:false,error:'Not enough overlapping composite history for V4',candles:f.data.length,required:VW+110,errors:f.errors,ts:Date.now()});const started=Date.now(),t=trainV4(f.data),p=predictV4(f.data,t);return res.status(200).json({ok:true,version:'V4',source:'MULTI-EXCHANGE MEDIAN',exchanges:Object.keys(f.feeds),candles:f.data.length,prediction:p,engine:{population:VP,inputNeurons:VI,outputNeurons:1,signalNeurons:1,neighbors:3,lutEntries:VL,windowWidth:VW,mutationSteps:VM,lutEditsPerStep:2,roots:VROOTS,survivors:VSURV,trainWindows:t.trainWindows,maxDepth:t.maxDepth,meanAcceptedMutations:+t.accepted.toFixed(1),meanMutationGain:+t.gain.toFixed(2),holdoutAccuracy:t.hold,encoding:'custom QUBIC 18-trit features',selfClocked:true,bitExactMainnet:false},latest:f.data.at(-1),series:f.data.slice(-168).map(x=>({time:x.time,close:x.close,agreement:x.agreement})),elapsedMs:Date.now()-started,errors:f.errors,ts:Date.now()})}
if(useComposite){const f=await compositeFeed(limit),data=f.data;if(data.length<250)return res.status(503).json({ok:false,error:'Not enough overlapping composite history',counts:Object.fromEntries(Object.entries(f.feeds).map(([k,v])=>[k,v.length])),errors:f.errors,ts:Date.now()});return res.status(200).json({ok:true,interval:'1h',source:'MULTI-EXCHANGE MEDIAN',exchanges:Object.keys(f.feeds),activity:a.scores,errors:f.errors,candles:data,latestAgreement:data.at(-1)?.agreement??null,ts:Date.now()})}
const ranked=Object.entries(a.scores).sort((x,y)=>y[1].score-x[1].score);let chosen=a.chosen;const top=ranked[0]?.[1]?.score||0;if(prefer&&a.scores[prefer]&&a.scores[prefer].score>=top*.65)chosen=prefer;const order=[chosen,...ranked.map(x=>x[0]),'GATE'].filter((v,i,s)=>v&&s.indexOf(v)===i);let data=[],source=null;const minHistory=Math.min(80,Math.max(40,Math.floor(limit*.15))),rejected={};for(const ex of order){try{const d=(await candles(ex,iv,limit)).filter(x=>Number.isFinite(x.time)&&x.open>0&&x.high>0&&x.low>0&&x.close>0).sort((x,y)=>x.time-y.time);if(d.length>=minHistory){data=d;source=ex;break}rejected[ex]=d.length}catch(e){rejected[ex]=String(e?.message||e)}}if(!data.length)return res.status(503).json({ok:false,error:'No active exchange has enough candle history',interval:iv,minHistory,rejected,ts:Date.now()});res.status(200).json({ok:true,interval:iv,source,activity:a.scores,minHistory,rejected,candles:data,ts:Date.now()})}catch(e){res.status(503).json({ok:false,error:String(e?.message||e),interval:iv,ts:Date.now()})}}
