const SOURCES=[
 {name:'GATE',url:'https://api.gateio.ws/api/v4/spot/order_book?currency_pair=QUBIC_USDT&limit=50',parse:x=>({bids:x.bids,asks:x.asks,ts:x.current||Date.now()})},
 {name:'MEXC',url:'https://api.mexc.com/api/v3/depth?symbol=QUBICUSDT&limit=50',parse:x=>({bids:x.bids,asks:x.asks,ts:Date.now()})},
 {name:'BITGET',url:'https://api.bitget.com/api/v3/market/orderbook?category=SPOT&symbol=QUBICUSDT&limit=50',parse:x=>({bids:x.data?.b||x.data?.bids,asks:x.data?.a||x.data?.asks,ts:+(x.data?.ts||x.requestTime)||Date.now()})},
 {name:'COINEX',url:'https://api.coinex.com/v2/spot/depth?market=QUBICUSDT&limit=50&interval=0',parse:x=>({bids:x.data?.depth?.bids,asks:x.data?.depth?.asks,ts:+x.data?.depth?.updated_at||Date.now()})},
 {name:'LBANK',url:'https://api.lbank.info/v2/depth.do?symbol=qubic_usdt&size=50',parse:x=>({bids:x.data?.bids,asks:x.data?.asks,ts:+(x.data?.timestamp||x.ts)||Date.now()})}
];
const num=x=>Number(x);
function median(a){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;let m=a.length>>1;return a.length%2?a[m]:(a[m-1]+a[m])/2}
function analyse(name,book){let bids=(book.bids||[]).map(x=>[num(x[0]),num(x[1])]).filter(x=>x[0]>0&&x[1]>0).sort((a,b)=>b[0]-a[0]),asks=(book.asks||[]).map(x=>[num(x[0]),num(x[1])]).filter(x=>x[0]>0&&x[1]>0).sort((a,b)=>a[0]-b[0]);if(!bids.length||!asks.length)throw Error('empty book');let bid=bids[0][0],ask=asks[0][0],mid=(bid+ask)/2,spreadBps=(ask-bid)/mid*10000;if(!Number.isFinite(mid)||spreadBps<0||spreadBps>500)throw Error('invalid spread');let depth=(levels,side,pct)=>levels.filter(([p])=>side==='bid'?p>=mid*(1-pct):p<=mid*(1+pct)).reduce((s,[p,q])=>s+p*q,0);let bid05=depth(bids,'bid',.005),ask05=depth(asks,'ask',.005),bid1=depth(bids,'bid',.01),ask1=depth(asks,'ask',.01),imb05=(bid05-ask05)/Math.max(1,bid05+ask05),imb1=(bid1-ask1)/Math.max(1,bid1+ask1);let topBid=bids.slice(0,10).reduce((s,[p,q])=>s+p*q,0),topAsk=asks.slice(0,10).reduce((s,[p,q])=>s+p*q,0),topImb=(topBid-topAsk)/Math.max(1,topBid+topAsk);return{name,mid,spreadBps,bid05,ask05,bid1,ask1,imbalance:.5*imb05+.3*imb1+.2*topImb,ts:book.ts||Date.now()}}
async function one(s){let c=new AbortController(),t=setTimeout(()=>c.abort(),3500);try{let r=await fetch(s.url,{cache:'no-store',signal:c.signal,headers:{accept:'application/json','user-agent':'QubicIntelligence/1.0'}});if(!r.ok)throw Error(String(r.status));return analyse(s.name,s.parse(await r.json()))}finally{clearTimeout(t)}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store, max-age=0');res.setHeader('Access-Control-Allow-Origin','*');let settled=await Promise.allSettled(SOURCES.map(one)),books=settled.filter(x=>x.status==='fulfilled').map(x=>x.value),failed=settled.map((x,i)=>x.status==='rejected'?SOURCES[i].name:null).filter(Boolean);if(!books.length)return res.status(503).json({ok:false,error:'No order books available',failed,ts:Date.now()});let imbs=books.map(x=>x.imbalance),imbalance=median(imbs),buyVotes=imbs.filter(x=>x>.08).length,sellVotes=imbs.filter(x=>x<-.08).length,neutralVotes=books.length-buyVotes-sellVotes,consensus=buyVotes>sellVotes?'BUY':sellVotes>buyVotes?'SELL':'MIXED',agreement=Math.max(buyVotes,sellVotes,neutralVotes)/books.length,mid=median(books.map(x=>x.mid)),spreadBps=median(books.map(x=>x.spreadBps));res.status(200).json({ok:true,mid,imbalance,consensus,agreement,buyVotes,sellVotes,neutralVotes,sources:books.length,spreadBps,books,failed,ts:Date.now()})}